### ISSUE TITLE
Jaguar XF S (x260) missing items

### ISSUE THREAD

**Issue by jayjaytyper** [msp1974/homeassistant-jlrincontrol#10]
Hello, First of all great work.

In order to help you with missing item i created the list below. that i know the status are there if i run the jlrpy.py manually (just never had the knowledge to its this working in HA)

Sunroof - Status {'key': 'IS_SUNROOF_OPEN', 'value': 'FALSE'}

FYI 
The DPF is not there on the API even tho i have the Diesel 

Happy to help with any testing if required

**Comment by msp1974** [comment]
Will add in the next couple of days. One thing i was wondering about this is that in the attributes it has a roof opens parameter. Didnt know if this related to whether vehicle has a sunroof or just a drop top. Can you let me know what this attribute is for yours. If it does signify then we can only show this for cars with sunroof.

**Comment by jayjaytyper** [comment]
if i get attributes i have `'JLR_PROVISIONED_MODE', 'roofType': 'SUNROOF'}` that the only thing i have roof opens parameter is not there

**Comment by msp1974** [comment]
Sorry yes, this is the one. Great, we can use this to determine to show the sunroof open status. Do you think this should be under windows. I think it makes more sense as doors are part of a lock device and can be unlocked from the sensor.

**Comment by jayjaytyper** [comment]
Yes agree windows is the best place for it.

**Comment by jayjaytyper** [comment]
a strange one car is due for a service but it shows as this, any way to make it say it needs a service? not sure what status point to look at

![image](https://user-images.githubusercontent.com/43699296/79504537-f5db6780-802a-11ea-9ab3-5e00879f15e2.png)

**Comment by msp1974** [comment]
Yes, there are other params i have not yet added that show mileage to service. These are already on the list to add.

**Comment by msp1974** [comment]
Ok, have updated this to 0.2alpha today including:
Sunroof now shows in windows if fitted
Last updated time from car in vehicle info
Additional service info sensors attributes for distance to service, adblue fill litres etc
Please see change log in readme.

**Comment by jayjaytyper** [comment]
i have updated but i it is still missing the sunroof 

![image](https://user-images.githubusercontent.com/43699296/79603043-7b225300-80e3-11ea-8af5-0ba1bfbf223c.png)
 Distance to service is working tho. but no adblue 

![image](https://user-images.githubusercontent.com/43699296/79603089-93926d80-80e3-11ea-913b-62b00b9d82bf.png)

**Comment by msp1974** [comment]
Apologies, I really need to work out a better way to test things I don't have on my car.  Should work on  sunroof now in master branch update.

On the DPF, it must be that your car is not reporting this.  There should also be additional sensor info on car service info relating to this.  It will not show them if they are not presented in the api data.  If you want to send me a data output I can look at this to see exactly what your car sends/doesn't send.  See update in readme for how to enable data debugging.

**Comment by msp1974** [comment]
FYI, this is what mine shows in info
![image](https://user-images.githubusercontent.com/11211952/79608244-8928a180-80ec-11ea-8dee-e9a7318245f7.png)

**Comment by jayjaytyper** [comment]
No need to apologize. I can test any think you need if my car allows me to :)

Sunroof is now there 

`2020-04-17 20:45:59 DEBUG (MainThread) [custom_components.jlrincontrol] ATTRIBUTE DATA - {'engineCode': '3.0', 'seatsQuantity': 5, 'exteriorColorName': 'White', 'exteriorCode': 'White', 'interiorColorName': None, 'interiorCode': None, 'tyreDimensionCode': None, 'tyreInflationPressureLightCode': None, 'tyreInflationPressureHeavyCode': None, 'fuelType': 'Diesel', 'fuelTankVolume': None, 'grossWeight': 1890, 'modelYear': 2018, 'constructionDate': None, 'deliveryDate': None, 'numberOfDoors': 4, 'country': 'GBR', 'registrationNumber': '*****', 'carLocatorMapDistance': None, 'vehicleBrand': 'Jaguar', 'vehicleType': 'XF', 'vehicleTypeCode': 'X260', 'bodyType': '4 Door SWB', 'gearboxCode': 'Automatic', 'availableServices': [{'serviceType': 'ALOFF', 'vehicleCapable': True, 'serviceEnabled': True}, {'serviceType': 'BCALL', 'vehicleCapable': True, 'serviceEnabled': True}, {'serviceType': 'CI', 'vehicleCapable': True, 'serviceEnabled': True}, {'serviceType': 'ECALL', 'vehicleCapable': True, 'serviceEnabled': True}, {'serviceType': 'HBLF', 'vehicleCapable': True, 'serviceEnabled': True}, {'serviceType': 'JL', 'vehicleCapable': True, 'serviceEnabled': True}, {'serviceType': 'RDL', 'vehicleCapable': True, 'serviceEnabled': True}, {'serviceType': 'RDU', 'vehicleCapable': True, 'serviceEnabled': True}, {'serviceType': 'REOFF', 'vehicleCapable': True, 'serviceEnabled': True}, {'serviceType': 'REON', 'vehicleCapable': True, 'serviceEnabled': True}, {'serviceType': 'SVT', 'vehicleCapable': True, 'serviceEnabled': True}, {'serviceType': 'TN', 'vehicleCapable': True, 'serviceEnabled': True}, {'serviceType': 'UPS', 'vehicleCapable': True, 'serviceEnabled': True}, {'serviceType': 'VHC', 'vehicleCapable': True, 'serviceEnabled': True}, {'serviceType': 'VHS', 'vehicleCapable': True, 'serviceEnabled': True}], 'timeFullyAccessible': None, 'timePartiallyAccessible': None, 'subscriptionType': None, 'subscriptionStartDate': None, 'subscriptionStopDate': None, 'capabilities': [{'capability': 'A03C', 'capabilityClass': 'JA03'}, {'capability': 'B09F', 'capabilityClass': 'JB09'}, {'capability': 'B28M', 'capabilityClass': 'JB28'}, {'capability': 'C88A', 'capabilityClass': 'JC88'}, {'capability': 'C31Q', 'capabilityClass': 'JC31'}, {'capability': 'RJC', 'capabilityClass': 'JTRM'}, {'capability': 'FPDE', 'capabilityClass': 'JFAC'}, {'capability': 'P50T', 'capabilityClass': 'JP50'}, {'capability': 'JSCZ', 'capabilityClass': 'JSYC'}, {'capability': 'H41C', 'capabilityClass': 'JH41'}, {'capability': 'H44P', 'capabilityClass': 'JH44'}, {'capability': 'L01B', 'capabilityClass': 'JGRP'}, {'capability': 'A50C', 'capabilityClass': 'JA50'}, {'capability': 'B18Z', 'capabilityClass': 'JB18'}, {'capability': 'D17C', 'capabilityClass': 'JD17'}, {'capability': 'C35A', 'capabilityClass': 'JC35'}, {'capability': 'F97A', 'capabilityClass': 'JF97'}, {'capability': 'H53K', 'capabilityClass': 'JH53'}, {'capability': 'H54J', 'capabilityClass': 'JH54'}, {'capability': 'A85K', 'capabilityClass': 'JA85'}, {'capability': 'A20K', 'capabilityClass': 'JA20'}, {'capability': 'A90D', 'capabilityClass': 'JA90'}, {'capability': 'H72C', 'capabilityClass': 'JH72'}, {'capability': 'B55A', 'capabilityClass': 'JB55'}, {'capability': 'Z03Q', 'capabilityClass': 'JZ03'}, {'capability': 'V00A', 'capabilityClass': 'JMKT'}, {'capability': 'F42B', 'capabilityClass': 'JF42'}, {'capability': 'C73D', 'capabilityClass': 'JC73'}, {'capability': 'ZJ04', 'capabilityClass': 'JPAG'}, {'capability': 'A41B', 'capabilityClass': 'JA41'}, {'capability': 'A44D', 'capabilityClass': 'JA44'}, {'capability': 'A87A', 'capabilityClass': 'JA87'}, {'capability': 'G60A', 'capabilityClass': 'JG60'}, {'capability': 'A21C', 'capabilityClass': 'JA21'}, {'capability': 'C53L', 'capabilityClass': 'JWHE'}, {'capability': 'D90L', 'capabilityClass': 'JD90'}, {'capability': 'Y18B', 'capabilityClass': 'JMYP'}, {'capability': 'G56A', 'capabilityClass': 'JG56'}, {'capability': 'KPDE', 'capabilityClass': 'JCAR'}, {'capability': 'G12E', 'capabilityClass': 'JG12'}, {'capability': 'F28S', 'capabilityClass': 'JF28'}, {'capability': 'Z19Z', 'capabilityClass': 'JZ19'}, {'capability': 'B41T', 'capabilityClass': 'JB40'}, {'capability': 'H48W', 'capabilityClass': 'JH48'}, {'capability': 'Z80Z', 'capabilityClass': 'JZ60'}, {'capability': 'A40E', 'capabilityClass': 'JA40'}, {'capability': 'F29Z', 'capabilityClass': 'JF29'}, {'capability': 'H76C', 'capabilityClass': 'JH76'}, {'capability': 'Z42Z', 'capabilityClass': 'JZ42'}, {'capability': 'G48S', 'capabilityClass': 'JG48'}, {'capability': 'C10R', 'capabilityClass': 'JC10'}, {'capability': 'F03B', 'capabilityClass': 'JF03'}, {'capability': 'G59R', 'capabilityClass': 'JG59'}, {'capability': 'F52C', 'capabilityClass': 'JF52'}, {'capability': 'F53B', 'capabilityClass': 'JF53'}, {'capability': 'F54A', 'capabilityClass': 'JF54'}, {'capability': 'F09C', 'capabilityClass': 'JF09'}, {'capability': 'C12Z', 'capabilityClass': 'JC12'}, {'capability': 'H71Z', 'capabilityClass': 'H71A'}, {'capability': 'H01E', 'capabilityClass': 'JZXC'}, {'capability': 'Z69I', 'capabilityClass': 'JZ69'}, {'capability': 'F49F', 'capabilityClass': 'JF49'}, {'capability': 'B71L', 'capabilityClass': 'JB71'}, {'capability': 'B66C', 'capabilityClass': 'JB66'}, {'capability': 'B90A', 'capabilityClass': 'JB90'}, {'capability': 'B84A', 'capabilityClass': 'JB84'}, {'capability': 'B86A', 'capabilityClass': 'JB86'}, {'capability': 'Z77Z', 'capabilityClass': 'JZ77'}, {'capability': 'D97A', 'capabilityClass': 'JD97'}, {'capability': 'C70F', 'capabilityClass': 'JC70'}, {'capability': 'H46W', 'capabilityClass': 'JH46'}, {'capability': 'D44A', 'capabilityClass': 'JD44'}, {'capability': 'S69A', 'capabilityClass': 'JS69'}, {'capability': 'B37A', 'capabilityClass': 'JB37'}, {'capability': 'U01A', 'capabilityClass': 'JU01'}, {'capability': 'U03B', 'capabilityClass': 'JU03'}, {'capability': 'U05B', 'capabilityClass': 'JU05'}, {'capability': 'U07A', 'capabilityClass': 'JU07'}, {'capability': 'U09A', 'capabilityClass': 'JU09'}, {'capability': 'U11F', 'capabilityClass': 'JU11'}, {'capability': 'U13A', 'capabilityClass': 'JU13'}, {'capability': 'U15C', 'capabilityClass': 'JU15'}, {'capability': 'U17B', 'capabilityClass': 'JU17'}, {'capability': 'B93A', 'capabilityClass': 'JB93'}, {'capability': 'D89A', 'capabilityClass': 'JD89'}, {'capability': 'D84A', 'capabilityClass': 'JD84'}, {'capability': 'B98A', 'capabilityClass': 'JB98'}, {'capability': 'B99B', 'capabilityClass': 'JB99'}, {'capability': 'D83Z', 'capabilityClass': 'JD83'}, {'capability': 'D74Z', 'capabilityClass': 'JD74'}, {'capability': 'D79A', 'capabilityClass': 'JD79'}, {'capability': 'B95Z', 'capabilityClass': 'JB95'}, {'capability': 'B96Z', 'capabilityClass': 'JB96'}, {'capability': 'B97F', 'capabilityClass': 'JB97'}, {'capability': 'D87Z', 'capabilityClass': 'JD87'}, {'capability': 'A71A', 'capabilityClass': 'JA71'}, {'capability': 'A52Z', 'capabilityClass': 'JA52'}, {'capability': 'H85E', 'capabilityClass': 'JH85'}, {'capability': 'Z28Z', 'capabilityClass': 'JZ28'}, {'capability': 'H43A', 'capabilityClass': 'JH43'}, {'capability': 'D45D', 'capabilityClass': 'JD45'}, {'capability': 'SCDB', 'capabilityClass': 'JPCS'}, {'capability': 'SDNC', 'capabilityClass': 'JPDC'}, {'capability': 'SFMT', 'capabilityClass': 'JPSU'}, {'capability': 'Z93L', 'capabilityClass': 'JB60'}, {'capability': 'Z79Z', 'capabilityClass': 'JZ70'}, {'capability': 'B69A', 'capabilityClass': 'JB69'}, {'capability': 'C39A', 'capabilityClass': 'JC39'}, {'capability': 'G67A', 'capabilityClass': 'JG67'}, {'capability': 'Z04Z', 'capabilityClass': 'JZ04'}, {'capability': 'D95Z', 'capabilityClass': 'JD95'}, {'capability': 'Z85Z', 'capabilityClass': 'JZ85'}, {'capability': 'Z36Z', 'capabilityClass': 'JZ36'}, {'capability': 'Z86Z', 'capabilityClass': 'JZ86'}, {'capability': 'F19Z', 'capabilityClass': 'JF19'}, {'capability': 'B39Z', 'capabilityClass': 'JB39'}, {'capability': '900C', 'capabilityClass': 'ZZXY'}, {'capability': 'Z12Z', 'capabilityClass': 'JZ12'}, {'capability': 'Z13Z', 'capabilityClass': 'JZ13'}, {'capability': 'Z16Z', 'capabilityClass': 'JZ16'}, {'capability': 'S52N', 'capabilityClass': 'JS52'}, {'capability': 'A60R', 'capabilityClass': 'JA60'}, {'capability': 'C05Z', 'capabilityClass': 'JC05'}, {'capability': 'H58A', 'capabilityClass': 'JH58'}, {'capability': 'B79A', 'capabilityClass': 'JB79'}, {'capability': 'F45C', 'capabilityClass': 'JF45'}, {'capability': 'S54A', 'capabilityClass': 'JS54'}, {'capability': 'S55C', 'capabilityClass': 'JS55'}, {'capability': 'F10A', 'capabilityClass': 'JF10'}, {'capability': 'H50A', 'capabilityClass': 'JH50'}, {'capability': 'C18Z', 'capabilityClass': 'JC18'}, {'capability': 'F16A', 'capabilityClass': 'JF16'}, {'capability': 'G62Z', 'capabilityClass': 'JG62'}, {'capability': 'C91C', 'capabilityClass': 'JC91'}, {'capability': 'G64D', 'capabilityClass': 'JG64'}, {'capability': 'F14A', 'capabilityClass': 'JF14'}, {'capability': 'C15A', 'capabilityClass': 'JC15'}, {'capability': 'C17Z', 'capabilityClass': 'JC17'}, {'capability': 'C71D', 'capabilityClass': 'JC71'}, {'capability': 'H51A', 'capabilityClass': 'JH51'}, {'capability': 'D70C', 'capabilityClass': 'JD70'}, {'capability': 'D71B', 'capabilityClass': 'JD71'}, {'capability': 'D72A', 'capabilityClass': 'JD72'}, {'capability': 'TR35', 'capabilityClass': 'JTRS'}, {'capability': 'C74C', 'capabilityClass': 'JC74'}, {'capability': 'E05C', 'capabilityClass': 'JE05'}, {'capability': 'Z76Z', 'capabilityClass': 'JZ76'}, {'capability': '1AQ', 'capabilityClass': 'JPNC'}, {'capability': 'B23K', 'capabilityClass': 'JB23'}, {'capability': 'H60C', 'capabilityClass': 'JH60'}, {'capability': 'C78B', 'capabilityClass': 'JC78'}, {'capability': 'D47A', 'capabilityClass': 'JD47'}, {'capability': 'A40Z', 'capabilityClass': 'JA39'}, {'capability': 'S53Z', 'capabilityClass': 'JS53'}, {'capability': 'C80E', 'capabilityClass': 'JC80'}, {'capability': 'C83E', 'capabilityClass': 'JC83'}, {'capability': 'J95A', 'capabilityClass': 'JC95'}, {'capability': 'F11C', 'capabilityClass': 'JF11'}, {'capability': 'Z61Z', 'capabilityClass': 'JZ61'}, {'capability': 'B44V', 'capabilityClass': 'JB44'}, {'capability': 'G10Z', 'capabilityClass': 'JG10'}, {'capability': 'D07J', 'capabilityClass': 'JD07'}, {'capability': 'L58A', 'capabilityClass': 'JLIT'}, {'capability': 'G52Z', 'capabilityClass': 'JG52'}, {'capability': 'C11A', 'capabilityClass': 'JC11'}, {'capability': 'Z88D', 'capabilityClass': 'JZ88'}, {'capability': 'L83B', 'capabilityClass': 'JL83'}, {'capability': 'G73Z', 'capabilityClass': 'JG73'}, {'capability': 'D96A', 'capabilityClass': 'JD96'}, {'capability': 'SPDE', 'capabilityClass': 'JPST'}, {'capability': 'RPDE', 'capabilityClass': 'JBLT'}, {'capability': 'Z59X', 'capabilityClass': 'JZ56'}, {'capability': 'C40D', 'capabilityClass': 'JWHS'}, {'capability': 'F95T', 'capabilityClass': 'JSTR'}, {'capability': 'D53B', 'capabilityClass': 'JD53'}, {'capability': 'H84Z', 'capabilityClass': 'JH84'}, {'capability': 'B20Z', 'capabilityClass': 'JB20'}, {'capability': 'VSAZ', 'capabilityClass': 'JVRA'}, {'capability': 'G12T', 'capabilityClass': 'JG11'}, {'capability': 'Z16U', 'capabilityClass': 'JZ15'}, {'capability': 'HPDB', 'capabilityClass': 'JHED'}, {'capability': 'G51Z', 'capabilityClass': 'JG51'}, {'capability': 'H73Z', 'capabilityClass': 'JH73'}, {'capability': 'H10E', 'capabilityClass': 'JH10'}, {'capability': 'C42R', 'capabilityClass': 'JC42'}, {'capability': 'C25A', 'capabilityClass': 'JC25'}, {'capability': 'P52R', 'capabilityClass': 'JP52'}, {'capability': 'B05G', 'capabilityClass': 'JB05'}, {'capability': 'H69K', 'capabilityClass': 'JH69'}, {'capability': 'C13A', 'capabilityClass': 'JC13'}, {'capability': 'C89B', 'capabilityClass': 'JC89'}, {'capability': 'F04B', 'capabilityClass': 'JF04'}, {'capability': 'A02M', 'capabilityClass': 'JA02'}, {'capability': 'B07X', 'capabilityClass': 'JB07'}, {'capability': 'B51A', 'capabilityClass': 'JB51'}, {'capability': 'H02J', 'capabilityClass': 'JZXD'}, {'capability': 'H03Q', 'capabilityClass': 'JZXE'}, {'capability': 'C14A', 'capabilityClass': 'JC14'}, {'capability': 'H75A', 'capabilityClass': 'JH75'}, {'capability': 'B15Q', 'capabilityClass': 'JB15'}, {'capability': 'B08L', 'capabilityClass': 'JB08'}, {'capability': 'B21G', 'capabilityClass': 'JB21'}, {'capability': 'S57B', 'capabilityClass': 'JS57'}, {'capability': 'B73J', 'capabilityClass': 'JB73'}, {'capability': 'B87A', 'capabilityClass': 'JB87'}, {'capability': 'B88A', 'capabilityClass': 'JB88'}, {'capability': 'B89A', 'capabilityClass': 'JB89'}, {'capability': 'B85A', 'capabilityClass': 'JB85'}, {'capability': 'B91A', 'capabilityClass': 'JB91'}, {'capability': 'B92A', 'capabilityClass': 'JB92'}, {'capability': 'C61F', 'capabilityClass': 'JC61'}, {'capability': 'B68B', 'capabilityClass': 'JB68'}, {'capability': 'B65A', 'capabilityClass': 'JB65'}, {'capability': 'H57A', 'capabilityClass': 'JH57'}, {'capability': 'A61D', 'capabilityClass': 'JA61'}, {'capability': 'B82A', 'capabilityClass': 'JB82'}, {'capability': 'B83A', 'capabilityClass': 'JB83'}, {'capability': 'G27Z', 'capabilityClass': 'ZZYM'}, {'capability': 'G33B', 'capabilityClass': 'ZZZC'}, {'capability': 'F46C', 'capabilityClass': 'JF46'}, {'capability': 'G36B', 'capabilityClass': 'ZZZF'}, {'capability': '36AE', 'capabilityClass': 'KA36'}, {'capability': 'G18C', 'capabilityClass': 'JG18'}, {'capability': '34AB', 'capabilityClass': 'KA34'}, {'capability': 'G23Z', 'capabilityClass': 'ZZYF'}, {'capability': 'G45A', 'capabilityClass': 'ZZZT'}, {'capability': 'F21E', 'capabilityClass': 'JF21'}, {'capability': 'A22Z', 'capabilityClass': 'JA22'}, {'capability': 'G61Z', 'capabilityClass': 'JG61'}, {'capability': 'F20A', 'capabilityClass': 'JF20'}, {'capability': 'A46B', 'capabilityClass': 'JA46'}, {'capability': 'G75A', 'capabilityClass': 'JG75'}], 'nickname': '******', 'telematicsDevice': {'serialNumber': '*********', 'imei': None}, 'deviceState': 'JLR_PROVISIONED_MODE', 'roofType': 'SUNROOF'}
2020-04-17 20:46:00 DEBUG (MainThread) [custom_components.jlrincontrol] STATUS DATA - {'TU_STATUS_PRIMARY_VOLT': '0.0', 'TU_STATUS_PRIMARY_CHARGE_PERCENT': '0', 'TU_STATUS_GSM_MODEM': 'FUNCTIONING', 'DOOR_IS_ALL_DOORS_LOCKED': 'TRUE', 'EV_IS_PLUGGED_IN': 'UNKNOWN', 'CLIMATE_STATUS_TIMER1_DAY': '0', 'BATTERY_STATUS': 'BATTERY_3_4', 'WASHER_FLUID_WARN': 'NORMAL', 'DOOR_FRONT_LEFT_POSITION': 'CLOSED', 'TU_STATUS_SLEEP_CYCLES_START_TIME': '2015-10-30T19:48:12.000Z', 'TU_STATUS_GNSS_ANTENNA': 'FUNCTIONING', 'DOOR_REAR_RIGHT_POSITION': 'CLOSED', 'ENGINE_COOLANT_TEMP': '84', 'CLIMATE_STATUS_REMAINING_RUNTIME': '30', 'DISTANCE_TO_EMPTY_FUEL': '97', 'ODOMETER_MILES_RESOLUTION': 'false', 'SERVICE_MODE_START': '2019-10-15T16:08:25+0000', 'TYRE_STATUS_REAR_LEFT': 'NORMAL', 'ODOMETER_MILES': '30084', 'TU_STATUS_SECONDARY_VOLT': '4.1000000000000005', 'SRS_STATUS': 'SRS_NOT_DEPLOYED', 'DOOR_REAR_RIGHT_LOCK_STATUS': 'LOCKED', 'IS_PANIC_ALARM_TRIGGERED': 'UNKNOWN', 'EV_IS_CHARGING': 'UNKNOWN', 'BRAKE_FLUID_WARN': 'NORMAL', 'DOOR_FRONT_RIGHT_POSITION': 'CLOSED', 'DRV_SEAT_THIRD_ROW_INHIBITION': 'NOTINHIBITED', 'DOOR_REAR_LEFT_LOCK_STATUS': 'LOCKED', 'TU_STATUS_MOBILE_PHONE_CONNECTED': 'TRUE', 'DRV_SEAT_THIRD_ROW_STATUS': 'UNKNOWN', 'EXT_OIL_LEVEL_WARN': 'NORMAL', 'TU_STATUS_MIC': 'FUNCTIONING', 'TU_STATUS_POWER': 'MAIN_BATTERY', 'DOOR_ENGINE_HOOD_POSITION': 'CLOSED', 'TRANSPORT_MODE_START': '1970-01-01T00:00:00+0000', 'EXT_BULB_STATUS_LEFT_TURN_ANY': '0', 'ENG_COOLANT_LEVEL_WARN': 'NORMAL', 'TU_STATUS_INT_RTC': 'FUNCTIONING', 'WINDOW_REAR_RIGHT_STATUS': 'CLOSED', 'WINDOW_FRONT_RIGHT_STATUS': 'CLOSED', 'TYRE_STATUS_FRONT_LEFT': 'NORMAL', 'THEFT_ALARM_STATUS': 'ALARM_ARMED', 'IS_SUNROOF_OPEN': 'FALSE', 'ODOMETER': '48416000', 'EXT_KILOMETERS_TO_SERVICE': '1569', 'PAS_SEAT_SECOND_ROW_STATUS': 'UNKNOWN', 'TU_STATUS_DAYS_SINCE_GNSS_FIX': '3', 'TU_STATUS_BUTTONS': 'FUNCTIONING', 'PAS_SEAT_THIRD_ROW_STATUS': 'UNKNOWN', 'DOOR_ENGINE_HOOD_LOCK_STATUS': 'LOCKED', 'VEHICLE_STATE_TYPE': 'KEY_REMOVED', 'TYRE_STATUS_FRONT_RIGHT': 'NORMAL', 'PRIVACY_SWITCH': 'FALSE', 'CLIMATE_STATUS_TIMER1_MINUTE': '0', 'TU_STATUS_EXT_POWER': 'FUNCTIONING', 'LATEST_COMPLETE_CONFIG_UPDATE': '2019-11-13T07:12:43+0000', 'TU_STATUS_HANDSET': 'UNCERTAIN', 'BRAZIL_EVENT_MODE': 'FALSE', 'DOOR_FRONT_RIGHT_LOCK_STATUS': 'LOCKED', 'IS_CRASH_SITUATION': 'FALSE', 'TYRE_PRESSURE_REAR_RIGHT': '224', 'CLIMATE_STATUS_TIMER2_DAY': '0', 'TU_STATUS_CONFIG_VERSION': '31', 'DOOR_FRONT_LEFT_LOCK_STATUS': 'LOCKED', 'WINDOW_REAR_LEFT_STATUS': 'CLOSED', 'PAS_SEAT_FIRST_ROW_INHIBITION': 'UNKNOWN', 'DRV_SEAT_SECOND_ROW_STATUS': 'UNKNOWN', 'TU_STATUS_EXT_HANDSFREE': 'BROKEN', 'PAS_SEAT_FIRST_ROW_STATUS': 'UNKNOWN', 'CLIMATE_STATUS_FFH_REMAINING_RUNTIME': '0', 'CLIMATE_STATUS_VENTING_TIME': '21', 'TYRE_PRESSURE_FRONT_RIGHT': '222', 'FUEL_LEVEL_PERC': '15', 'CLIMATE_STATUS_TIMER2_MONTH': '0', 'PAS_SEAT_THIRD_ROW_INHIBITION': 'NOTINHIBITED', 'DOOR_IS_BOOT_LOCKED': 'TRUE', 'DOOR_BOOT_POSITION': 'CLOSED', 'IS_HEAD_LIGHTS_ON': 'UNKNOWN', 'TU_STATUS_CRASH_INPUT': 'FUNCTIONING', 'SERVICE_MODE_STOP': '2019-10-16T02:08:24+0000', 'CLIMATE_STATUS_TIMER2_MINUTE': '0', 'TYRE_PRESSURE_FRONT_LEFT': '224', 'IS_CAB_OPEN': 'FALSE', 'TU_STATUS_USES_EXTERNAL_GNSS': 'FALSE', 'ODOMETER_METER_RESOLUTION': 'true', 'CLIMATE_STATUS_TIMER2_HOUR': '0', 'TU_STATUS_GSM_EXT_ANTENNA': 'FUNCTIONING', 'ODOMETER_METER': '48416000', 'BATTERY_VOLTAGE': '12.0', 'TU_STATUS_SPEAKER': 'FUNCTIONING', 'TRANSPORT_MODE_STOP': '1970-01-01T00:00:00+0000', 'TYRE_PRESSURE_REAR_LEFT': '226', 'ENGINE_BLOCK': 'NORMAL_UNBLOCKED', 'CLIMATE_STATUS_TIMER_ACTIVATION_STATUS': 'FALSE', 'TU_STATUS_GNSS': 'FUNCTIONING', 'TU_STATUS_INT_POWER': 'FUNCTIONING', 'PAS_SEAT_SECOND_ROW_INHIBITION': 'NOTINHIBITED', 'EV_IS_PRECONDITIONING': 'UNKNOWN', 'EV_CHARGE_TYPE': 'UNKNOWN', 'WINDOW_FRONT_LEFT_STATUS': 'CLOSED', 'CLIMATE_STATUS_OPERATING_STATUS': 'OFF', 'DOOR_REAR_LEFT_POSITION': 'CLOSED', 'CLIMATE_STATUS_TIMER1_HOUR': '0', 'CLIMATE_STATUS_TIMER1_MONTH': '0', 'TYRE_STATUS_REAR_RIGHT': 'NORMAL', 'DRV_SEAT_SECOND_ROW_INHIBITION': 'INHIBITED', 'TU_ACTIVATION_STATUS': 'PROVISIONED', 'DOOR_BOOT_LOCK_STATUS': 'LOCKED', 'TU_STATUS_CAN': 'FUNCTIONING'}`

**Comment by msp1974** [comment]
It looks like there is no DPF or adblue info being sent by your car. Seems there is many differences in what sensors are presented on different cars.  Can you help test the dev branch update? See comments in issue #13. Thx

**Comment by msp1974** [comment]
@jayjaytyper can you let me know if the latest dev version has now fixed all your issues (well the ones that are not JLRs fault! ;-))

**Comment by jayjaytyper** [comment]
Yes it dose thank you. can you just update the docs to the correct paramter for 

 distance_units: <mi or km to override HA defualt>

i keep getting invalid config, i also not have the same sensors for my car 3 times but i think that could just be a problem for me as i was using HACS to track the changes before moving to dev

keep up the good work

**Comment by msp1974** [comment]
Updated readme. Should have been distance_unit.

**Comment by MZorzy** [comment]
@msp1974  about distance we have 5 data.
and look like on car is set meter:

'ODOMETER_MILES_RESOLUTION': 'false',
'ODOMETER_MILES': '30084',
'ODOMETER': '48416000', 
'ODOMETER_METER_RESOLUTION': 'true',
'ODOMETER_METER': '48416000',

may is better to use this false/true so HA is not different from car, and have not configuration entry?

**Comment by msp1974** [comment]
@MZorzy I had seen this but it is not correct.  My car is set to miles but these parameters show like yours.  
"ODOMETER_MILES_RESOLUTION":"false"
"ODOMETER_MILES":"21497"
"ODOMETER":"34598000"
"ODOMETER_METER_RESOLUTION":"true"
"ODOMETER_METER":"34598000"

Currently, HA is using the HA settings (which I assume will usually be the same as the car), however, HA does not support mix in UK of imperial and metric.  The config entry is only to override HA to show miles for distance and metric units for everything else.

It originally used the user preference settings in the JLR app but the JLR api frequently did not return these in the response.  If you keep making the request it would return 1 in 6 or 8 times which made me think this was not a reliable way either.

I think using HA is best and for everybody outside the UK, there is no need to add anything to config.yaml.

**Comment by MZorzy** [comment]
oh, agree. thankyou
