### ISSUE TITLE
Home Assistant - Node Red

### ISSUE THREAD

**Issue by McFarTech** [msp1974/homeassistant-jlrincontrol#100]
Hi. 

Has anyone got this to work with Node Red? I would like Node Red to turn my climate on each day at a set time.

**Comment by ismarslomic** [comment]
I don't see any reason why this integration should not work with Node Red. Have you tried? However, Im not using Node Red myself, as I can easily solve all my needs with Automation in Home Assistant. We can't give any support on Node Red in this repo, so I suggest that you ask this question in Node Red forum/github issues.
