### ISSUE TITLE
Two cars in one JLR account: HA warns about unique IDs

### ISSUE THREAD

**Issue by rich-kettlewell** [msp1974/homeassistant-jlrincontrol#101]
Logger: homeassistant.components.automation
Source: helpers/entity_platform.py:612
Integration: Automation (documentation, issues)
First occurred: 10:48:00 (1 occurrences)
Last logged: 10:48:00

Platform automation does not generate unique IDs. ID 1680099673138 already exists - ignoring automation.update_car_sensors

------

The above message happens because I have an automation which calls the "update_health_status" service on both my cars.
Is it a problem with the JLR integration?

**Comment by ismarslomic** [comment]
Related to #92

**Comment by msp1974** [comment]
This is the id you have given to your automation is not unique and not an issue of this integration.
