### ISSUE TITLE
Home Assistant - climate

### ISSUE THREAD

**Issue by Powerdata44** [msp1974/homeassistant-jlrincontrol#103]
Looking for entitie or possible create new entitie for climate icon in home assistant.

Touch icon then send message to LR to run Climate with possible count down time and set temperature.

If there is one please share of how to do it.

Regards David

**Comment by ismarslomic** [comment]
You can find the answer at https://github.com/msp1974/homeassistant-jlrincontrol/blob/master/Recipes.md
