### ISSUE TITLE
Setting temperature in service call `start_vehicle`

### ISSUE THREAD

**Issue by BNWEIN** [msp1974/homeassistant-jlrincontrol#107]
Hey

Happy new year! Sorry, i know this is really for bugs, but i wasnt sure where else to ask. I am using the below to remote start my car

name: Start Engine
        tap_action:
          action: call-service
          service: jlrincontrol.start_vehicle
          data:
            entity_id: sensor.my_new_car_info
            pin: <mypin>
            target_value: 43
            
I wanted to know what that "Target Value" is based on? I think when the car starts its preconditioning to 21.5 degrees C. I want to increase this, but was not sure what value to enter in the target value (assuming that is the temp value?

Any help appreciated?

Thanks

**Comment by ismarslomic** [comment]
target_value is the temperature to set (15.5 - 28.5C or 58 - 84F based on local HA units).

`start_vehicle` service is documented here: https://github.com/msp1974/homeassistant-jlrincontrol/blob/master/custom_components/jlrincontrol/services.yaml#L44 and the same documentation is visible in HA (see screenshot below).

![image](https://github.com/msp1974/homeassistant-jlrincontrol/assets/2174314/ec8058a1-3677-489c-b346-49c09d0b28ac)

**Comment by BNWEIN** [comment]
Thanks but i am a little confused because mine is set to 43, but the temp comes on at 21.5c?

**Comment by BNWEIN** [comment]
FYI HA Is set to C

**Comment by msp1974** [comment]
The api and old versions of the integration use a number range of 31-57 for the temp.  In C this is double the temp, in F this is temp - 27.

As this was confusing, later versions of the api allowed this value to be a temperature and we convert it.

As such, change yours to start using actual temp C.

**Comment by BNWEIN** [comment]
Noted, just tested this set at 23 and it worked. Thank you.
