### ISSUE TITLE
Unclear warning about deprecated services in 3.0.0 Beta 3

### ISSUE THREAD

**Issue by ismarslomic** [msp1974/homeassistant-jlrincontrol#123]
@msp1974:

Following services are considered as deprecated from v3.0.0, with following warning message in logs: `%s service has been deprecated.  Please update to use the new service for this function`

```python
DEPRECATED_SERVICES = [
    "update_health_status",
    "lock_vehicle",
    "unlock_vehicle",
    "reset_alarm",
    "honk_blink",
    "start_charging",
    "stop_charging",
]
```

1. It's not clear from the warning message what we mean with "please update" and which new service should be used instead. Can we provide more user friendly message to guide the user in right direction for migration? 
2. I guess we want the user to use the new buttons services in stead of direct service call? That works for manual service invocation, but what about automation? Do we want to force the users to use the "Press button" service to invoke the new button services? Im not completely sure we can completely remove these services, since they are required for the button services and useful in the automations.

**Comment by msp1974** [comment]
Yes, think we can make that message better.  Idea is that yes, you use the switch.turn_on/off and button.press service instead of the custom service as this is now redundant.  Will look at that.

Thanks for all great testing and feedback.

**Comment by Liam-Whiteside** [comment]
I'm also getting problems trying some of the new switches.

Charging (I'm not quite sure what this is supposed to do, but...), when switching on:
```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:238
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 14:13:05 (1 occurrences)
Last logged: 14:13:05

[140581630699328] 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2149, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2186, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 882, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 952, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/jlrincontrol/switch.py", line 81, in async_turn_on
    params = self.get_service_params(True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/jlrincontrol/switch.py", line 125, in get_service_params
    params = list(service.get("params"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
```

Climate : in the JLR app, I have the option of using either "Engine Climate" (which only works when the charge cable isn't plugged in) or "Electric Climate". If I try to use the new switch it doesn't appear to do anything (the car is currently plugged in, although I don't see any errors)

**Comment by msp1974** [comment]
This is not related to this issue, can you raise as a new issue and provide a diagnostics file and i will have a lok at it. Thx

**Comment by ismarslomic** [comment]
> Yes, think we can make that message better. Idea is that yes, you use the switch.turn_on/off and button.press service instead of the custom service as this is now redundant. Will look at that.

I have an idea on this one, will create PR

**Comment by ismarslomic** [comment]
@msp1974 I have suggested an adjustment to the warn message in #128.

btw: since we want the user to use the switch, button and lock services from v3.0.0 in stead of the old custom services, shouldn't we remove the new services in 3.0.0 from the `services.yaml`, so we can hide them in the HA UI? I guess that services can still be called directly from our code, even if they are not present in the `services.yaml`?

Im thinking of these new services added in v3.0.0:
- `enable_journey_recording`
- `disable_journey_recording`
- `enable_guardian_mode`
- `disable_guardian_mode`
- `enable_service_mode`
- `disable_service_mode`
- `enable_transport_mode`
- `disable_transport_mode`

**Comment by msp1974** [comment]
These new services serve a specific case of being able to provide a datetime until which is then different from just the switch_turn on service which uses a default 24h (or whatever is set in options).  I need to update docs to explain all this better.

The deprecated ones have no aditional options over the new entities.

Edit: except journey recording which yes i agree and maybe disabling services also have no merit, but is that then more confusing if enable services exist?

**Comment by ismarslomic** [comment]
> These new services serve a specific case of being able to provide a datetime until which is then different from just the switch_turn on service which uses a default 24h (or whatever is set in options).

Aha, I did not catch this. Agree with you that they are useful when they are different from the switches. Although the new service `enable_journey_recording` has no datetime field so it could maybe be removed?

Edit: saw your reply after i submitted :)

**Comment by ismarslomic** [comment]
> Edit: except journey recording which yes i agree and maybe disabling services also have no merit, but is that then more confusing if enable services exist?

Agreed - I think that we should expose disabling services for corresponding enabling services to make the "API" more complete and less confusing.

**Comment by msp1974** [comment]
ok, this is all now in dev.
