### ISSUE TITLE
Enabling Preconditioning by using switch does not update switch state to ON in 3.0.0 Beta 3

### ISSUE THREAD

**Issue by ismarslomic** [msp1974/homeassistant-jlrincontrol#127]
When switching `Preconditioning` _switch_ from `OFF` to `ON` the climate starts running on the vehicle, and the state of the `Climate` _sensor_ is updated to `Heating`, but the `Preconditioning` _switch_ has state `OFF`. 

I thought this was because of the state were not refreshed yet (polling interval) from the vehicle, but still after 9 minutes no state change of the switch.

<img width="347" alt="image" src="https://github.com/msp1974/homeassistant-jlrincontrol/assets/2174314/bc3f35a4-8e39-42e5-8d57-0b00382be1aa">

**Comment by msp1974** [comment]
I think it is possibly looking at the wrong status attribute.  Can you do a diag file when it is running preconditioning to see what is set.  I thought it would be EV_PRECONDITION_OPERATING_STATUS but maybe not, or it is set to something other than "ON".

It may also be that in PHEVs this is different again as Liam states in issue #125 that he has options for both Engine Climate and Electric Climate (depending on if charging or not) which I presume is both our Climate and Preconditioning switches.

**Comment by ismarslomic** [comment]
Diagnostic when precondition was disabled: 
[config_entry-jlrincontrol-precondition-disabled.json.txt](https://github.com/msp1974/homeassistant-jlrincontrol/files/14158017/config_entry-jlrincontrol-precondition-disabled.json.txt)

Diagnostic when precondition just got enabled:
[config_entry-jlrincontrol-precondition-enabled.json.txt](https://github.com/msp1974/homeassistant-jlrincontrol/files/14158018/config_entry-jlrincontrol-precondition-enabled.json.txt)

Diagnostic when precondition was enabled for 9 mins: 
[config_entry-jlrincontrol-precondition-enabled-in-9-mins.json.txt](https://github.com/msp1974/homeassistant-jlrincontrol/files/14158019/config_entry-jlrincontrol-precondition-enabled-in-9-mins.json.txt)

In v2 of this integration I created my custom binary_sensor for Precondition status and remaining time. This has been shared in the Recipes [here](https://github.com/msp1974/homeassistant-jlrincontrol/blob/master/Recipes.md#precondition-status-and-remaining-time-sensor).

> I choose to use binary_sensor (on/off) for precondition status, but the status actually got 3 states:
PRECLIM (on), OFF and STARTUP (starting). I did not bother to reflect all three states, but only on/off

Note that my car (I Pace Y21) does not support Climate switch, only Precondition (which I guess is the Electric Climate)? So I think Liam should help out with similar diagnostic file for his car for Engine and Electric Climate, so we can make logic supporting both?

**Comment by ismarslomic** [comment]
Basically logic should be:

```
if EV_PRECONDITION_OPERATING_STATUS == "OFF":
  switch status = "OFF"
else
  switch status = "ON"  # status is either PRECLIM or STARTUP
```

**Comment by ismarslomic** [comment]
Just tested with following changes to the code, and the switch got correct state. It even managed to turn the Preconditioning off as well 🥳 

``` python
climate_deactivated = get_value_match(
    vehicle.status_ev, "EV_PRECONDITION_OPERATING_STATUS", "OFF"
)

vehicle.tracked_status.climate_active = not climate_deactivated
```

maybe not the most elegant way to express it, but if you are fine with this logic I can commit this to dev?

**Comment by ismarslomic** [comment]
Thinking about your point about difference between Engine Climate (Climate) and Electric Climate (Precondition) switches, both switches uses the same state attribute `climate_active`, should we maybe separate them?

**Comment by ismarslomic** [comment]
Fixed and verified for both climate switches!
