### ISSUE TITLE
Version numbering Question

### ISSUE THREAD

**Issue by bobbinz** [msp1974/homeassistant-jlrincontrol#131]
This is absolutely not an issue, but I can't see where else to ask without bothering the forum.

I have been running 3.0.0beta4, all is working great and I like the new buttons rather than services.

HACS is telling me v2.2.5 is a newer version.

Is that really the case or will it break some stuff?

Should I press skip until v3 is actually released?

I wouldn't usually ask but I am just a bit confused by this in the changelog:
> chore(release): change release version from 3.0.0 to 2.2.5 by @ismarslomic in https://github.com/msp1974/homeassistant-jlrincontrol/pull/109

Thanks in advance!

**Comment by msp1974** [comment]
Yes to skip, I noticed this too.  Must be a feature of HACs.  We will release v3.0.0 formally soon, so wait for that.
