### ISSUE TITLE
JLR Api change?

### ISSUE THREAD

**Issue by danc89** [msp1974/homeassistant-jlrincontrol#134]
Is there gonna be an update to get around this API update? The creator of Wattcat has changed a "header" in the code or something and got that app back up and running.

**Comment by msp1974** [comment]
Have you updated to v2.2.6?

**Comment by danc89** [comment]
> Have you updated to v2.2.6?

I have now, all sorted! I couldn't see which version I was on and didn't see any dates on the updates
