### ISSUE TITLE
Please stop telling me about JLR blocking the api!

### ISSUE THREAD

**Issue by msp1974** [msp1974/homeassistant-jlrincontrol#136]
I really do appreciate people passing on information and sharing but .....

Fully aware of the JLR third party blocking issue.  Also fully aware that the devs over at Wattcat have found a workaround.

In fact, it was me who found the workaround and shared with ardevd to fix jlrpy and wattcat and other onward apps.

Before telling me again, please update to v2.2.6 or v3.0.0beta6, read some of the closed issues or check on the forum and see for yourself that we know and its fixed.

Rant over! 😘

Oh BTW, if they do it again, let me know! 😀

**Comment by bobbinz** [comment]
Looks like they did it again!

**Comment by msp1974** [comment]
God damn yes! It's been looked at.  Thanks

**Comment by msp1974** [comment]
Will close this issue for now and it can be tracked on #138
