### ISSUE TITLE
How to set climate temp with new switch in v3.0.0beta7

### ISSUE THREAD

**Issue by BNWEIN** [msp1974/homeassistant-jlrincontrol#139]
How do i set the temperature when using the new "switch.mycar_climate_engine" 

I previously used the "Jaguar Landrover InControl: start_vehicle" but i believe this is being depreciated. 

Thanks in advanced for any help!

**Comment by ismarslomic** [comment]
You can set the default target climate temperature in the Integration Configuration, which be used when using the Climate Switch UI component.

<img width="987" alt="image" src="https://github.com/msp1974/homeassistant-jlrincontrol/assets/2174314/06b63ea6-b4a5-4e91-a41b-f070ce72941b">

I think you should still be able to use the start_vehicle service, but it is deprecated and you are encouraged to use the switch.turn_on service in stead. But latter service does not allow sending target temperature as argument.

We will do more work on services and documentation of those, before finalising the beta release
