### ISSUE TITLE
Car Status Update - Suggestions

### ISSUE THREAD

**Issue by msp1974** [msp1974/homeassistant-jlrincontrol#14]
For all who have been trying this integration and providing great feedback, I would like your opinion on the following:

When you go into the InControl app, it requests an update from the car to get the latest info back to the JLR servers.  The HA integration queries this server data and presents in the sensors.  Now one obvious floor is that without these updates from the car, the data could be out of date if the car has not sent an update recently.  The info sensor (improved in the dev branch) now shows how long since the last update.

We now have a service (in the dev branch) to request this update but how should we do this?  My thoughts are this.

1) We would need to do this on some sort of interval for HA as there is no trigger to do otherwise.
2) If we do on a long interval then the data may not represent current status.
3) If we do on too short an interval, will JLR have an issue with this and block us?

So question is:
1) Do we set an interval in the integration to update on x period
2) Do we set a max interval and make the integration request an update if beyond this?
3) Do we just have the service available and people can choose to schedule this with an automation or create a button to force it?

**Comment by MZorzy** [comment]
here
https://documenter.getpostman.com/view/6250319/RznBMzqo?version=latest#3bc121c9-a4c9-4b85-b664-7a353ddab333
there is the API from wher jlrpy is done. 

and about get new data (health.status())
https://gitter.im/jlrpy/community?at=5db2bd3810bd4128a15b4cd1

**Comment by msp1974** [comment]
@MZorzy I was aware of the postman api but no the gitter thread.  However, not sure this gives us a good answer.  We can do the update manually in the HA integration.  The question is more how often we should do.  

The gitter chat is really talking about doing it on an iPace when charging but what about non EV and not charging.  What should HA do?  How much of an impact might frequent calls to health status have on battery.  What's the right balance between this and having up to date info?

**Comment by ghost** [comment]
If updates work via SMS they may costs JLR a little bit of money, but I cannot imagine the use of apps like this one being widespread enough for them to notice/care. However. I would probably not be comfortable with repetitive calls during long periods where I am not using the car, for fear of battery drain. So, manually creating a button to update would work best for me, or at most an option in the configuration.yaml to specify an update frequency which defaults to 'no automatic updates'.

Perhaps @ardevd has an opinion as he developed the API?

**Comment by ardevd** [comment]
You're technically paying for the service so I wouldn't be at all concerned. The car already transmits relatively large amounts of data over SMS (trip details for example) so the health status requests are not really significantly. Most of the data you request is just returned instantly from the cached data stored on the InControl server anyway.

It's probably good to be nice and not send a large number of requests every minute or so though.

**Comment by msp1974** [comment]
Ok, thanks for the suggestions all.  

I think best option is to have, as @stefanv84 has suggested, the ability to do a number of ways and have the ability to schedule (with default off), have a button that calls the service on demand or use an automation to have a few more smarts about when this is called (both using the in built service).  This way you can choose most appropriate method for your personal use cases.

**Comment by msp1974** [comment]
Latest v0.5alpha in dev branch has now been updated to include this.  See readme for instructions.

**Comment by MZorzy** [comment]
> have a button that calls the service on demand or use an automation 
oh yes please. upgrad when call integration service :-D

**Comment by msp1974** [comment]
All, very excited to announce that I have now released this a v1.0.  Big thanks for your input and help.  Please try it, play with it and (when we are all out of lock down) go drive your cars!

**Comment by msp1974** [comment]
Closing this issue as we have implemented a solution now.  Thanks for feedback.
