### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'vehicles'

### ISSUE THREAD

**Issue by tomw1964** [msp1974/homeassistant-jlrincontrol#141]
### The problem

I recently upgraded to v2.2.7 and the integration has stopped working.

2024-04-04 08:23:05.144 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry tom.XXXXX@XXXX.com for jlrincontrol
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/jlrincontrol/__init__.py", line 276, in async_setup_entry
    hass, config_entry, data.connection.vehicles, data
                        ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'vehicles'

### What version of JLR Home Assistant Integration has the issue?

v2.2.7

### What was the last working version of JLR Home Assistant Integration?

v2.2.6

### Vehicle type and model

RRS 510e

**Comment by msp1974** [comment]
Hi, sorry for late response.  Have been away for past 6 weeks but now back.  Is this still not working for you?  I have tested v2.2.7 against my RRS and all works as expected.

**Comment by tomw1964** [comment]
Just checked...looks like it started working on the 12th April. i have taken it to the dealer for a security update so maybe that helped...
![image](https://github.com/msp1974/homeassistant-jlrincontrol/assets/148999626/746e0116-6405-4065-82f0-04f3a19fbab8)

**Comment by msp1974** [comment]
> i have taken it to the dealer for a security update so maybe that helped...
Well it should certainly help make sure you keep hold of it! :-)

Glad its working now.  Will close this issue but please let me know if you have any other problems.
