### ISSUE TITLE
Unable to connect to the JLR InControl servers.

### ISSUE THREAD

**Issue by jfields87** [msp1974/homeassistant-jlrincontrol#144]
### The problem

Unable to connect to the JLR InControl servers.

### What version of JLR Home Assistant Integration has the issue?

2024.4.0

### Vehicle type and model

Landrover Discover 2020

**Comment by CadeusTheGreat** [comment]
Already in discussion. See issue #143

**Comment by MKtuzi** [comment]
Hi. I have the same problem. Integration does not log into incontrol “Unable to connect to the JLR InControl servers.” Logging in to the official web and ios application is hassle-free. Any guidance is welcome.

**Comment by msp1974** [comment]
This is because JLR have blocked access to the api the integration uses.  Please see open issues before raising new ones or commenting on them.  Thanks.  Will close as duplicate on #143

**Comment by MKtuzi** [comment]
Hi,
for more than 6 and a half years it won't let me reload the JLR
integrations. Useful integration with Siri shortcuts and assist button.. I
hope we will be informed soon about the future of the integration.
Thank you.
Regards, M.
