### ISSUE TITLE
No where to enter parameters in the UI

### ISSUE THREAD

**Issue by SimonB33** [msp1974/homeassistant-jlrincontrol#145]
### The problem

Instructions reference to paratmeters in Configuration -> Integrations in the UI. However no way seemingly to do so? No config file to amend either?

### What version of JLR Home Assistant Integration has the issue?

v2.2.7

### Vehicle type and model

Defender

**Comment by ptruman** [comment]
First of all, presently the integration is broken - so you won't get it setup and therefore won't get the screen.
If you DID get it setup, you'd see something like this:

![image](https://github.com/user-attachments/assets/052e4cdc-da5a-4ada-bc83-f5cc7bda2cee)

Basically change your temps and PIN.  It WAS working great before JLR decided to obfuscate/complicate their auth/login token process and until (or if) someone figures that out (or they publish the API) - it's broken :\

**Comment by ismarslomic** [comment]
Caused by broken integration as described in #143
