### ISSUE TITLE
Jlr

### ISSUE THREAD

**Issue by contiero75** [msp1974/homeassistant-jlrincontrol#147]
### The problem

Hi 
There are news about jlr?
Thanks
Stefano 

### Vehicle type and model

Evoque 2020

**Comment by contiero75** [comment]
Why closed?

**Comment by ismarslomic** [comment]
Because its duplicate of existing issue. Please read open issues before creating new ones

**Comment by contiero75** [comment]
ok
thanks



__________________________________________________
CONTIERO STEFANO
VIA BREO N.31
35020 CAMPAGNOLA DI BRUGINE (PD)
TELEFONO 348.38.30.800   
***@***.*** ***@***.***>
