### ISSUE TITLE
Vehicle Alert Sensors

### ISSUE THREAD

**Issue by zachamato** [msp1974/homeassistant-jlrincontrol#15]
Would be great to include some (not all) Vehicle Alert Sensors but the problem is these alerts come and go as the vehicle is updated. For example, something like the `ENGINE_ON` alert will stay for a few days, then disappear if the vehicle has not been on recently. `FUEL_LEVEL_LTRS` stays as an active alert almost always for me, and it has never been updated.

Would be nice to use these alerts in some HA automations. I have seen other alerts come up in the past but have not been able to pull a full list.

I will take a look at adding these on my own but pretty busy with work at the moment.

```json
    "vehicleAlerts": [
        {
            "key": "DIST_TO_SERVICE_KM",
            "value": "true",
            "active": true,
            "lastUpdatedTime": "2020-03-26T22:57:13+0000"
        },
        {
            "key": "ENGINE_ON",
            "value": "true",
            "active": true,
            "lastUpdatedTime": "2020-04-20T13:43:53+0000"
        },
        {
            "key": "FUEL_LEVEL_LTRS",
            "value": "5",
            "active": true,
            "lastUpdatedTime": "2019-01-25T08:42:01+0000"
        }
    ],

**Comment by msp1974** [comment]
Yeah, saw these but also saw the same issue, it seems that they are always there an never stop being active.  Not sure how to use them though in HA.  What were you thoughts?  Create a notification?

Working on getting multi vehicles working at the moment and then a couple of other things on the known issues list but could have a look at this after.

**Comment by zachamato** [comment]
Yeah I like the idea of using a notification in HA for some of the alerts. The ENGINE_ON alert would work as a sensor... maybe something like “Engine Last On: _lastUpdated_”

I also found some good information in the iOS .ipa file way back when I added the Remote Start functionality. There was a folder and files with a list of attributes and alerts names.

I’ll see what I can come up with soon

**Comment by msp1974** [comment]
That would be great.

**Comment by msp1974** [comment]
Just as a note, I have seen from some of the data from other cars, services that are not in the jlrpy and I do not know what they are/do.  Codes I have seen are below:

CI, JL, SVT, TN, UPS, VHC

Any knowledge about these would be great.

**Comment by zachamato** [comment]
Found the info I was referencing:
https://github.com/g1zm0e/JLRICRCommon-Redev/tree/master/feature_documentation

**Comment by msp1974** [comment]
This is great info. Will review fully and use to improve this.  Thanks.

**Comment by ismarslomic** [comment]
@zachamato: this issue has been stale for more then two years. Did you do any progress on the alert sensors, that you could share, and potentially submit as PR to this integration? Otherwise I think we need to close this issue.
