### ISSUE TITLE
Upgrade to HASS 109 gives errors

### ISSUE THREAD

**Issue by ganzewin** [msp1974/homeassistant-jlrincontrol#19]
Hello MSP1974,

I upgraded Home Assistant to version 0.109.0 and now receive the following warnings in the LOGS. 

Log Details (WARNING)
Logger: homeassistant.util.async_
Source: util/async_.py:120
First occurred: 9:12:48 PM (109 occurrences)
Last logged: 11:23:55 PM

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jlrincontrol doing I/O at custom_components/jlrincontrol/__init__.py, line 196: status = self.vehicle.get_status()
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jlrincontrol doing I/O at custom_components/jlrincontrol/__init__.py, line 232: self.position = self.vehicle.get_position()
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jlrincontrol doing I/O at custom_components/jlrincontrol/__init__.py, line 233: status = self.vehicle.get_status()
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jlrincontrol doing I/O at custom_components/jlrincontrol/__init__.py, line 239: self.wakeup = self.vehicle.get_wakeup_time()
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for jlrincontrol doing I/O at custom_components/jlrincontrol/services.py, line 39: status = service(**service_kwargs)

**Comment by msp1974** [comment]
I have put an updated version in dev branch.  Can you see if this now fixes these errors.

I notice you are not running the latest version so please see notes on breaking change.

**Comment by ganzewin** [comment]
Downloaded v 1.1.1 an hour ago and installed it following the README but the sensors are not appearing and the logbook shows the following;

I only see the entity lock.my_i_pace_doors but no others. 

Log Details (ERROR)
Logger: homeassistant.components.sensor
Source: custom_components/jlrincontrol/sensor.py:280
Integration: Sensor (documentation, issues)
First occurred: 2:15:21 PM (1 occurrences)
Last logged: 2:15:21 PM

Error while setting up jlrincontrol platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/jlrincontrol/sensor.py", line 55, in async_setup_platform
    devices.append(JLREVChargeSensor(hass, discovery_info))
  File "/config/custom_components/jlrincontrol/sensor.py", line 280, in __init__
    self._units = self._data.get_distance_units()
AttributeError: 'JLREVChargeSensor' object has no attribute '_data'

**Comment by msp1974** [comment]
Sorry, my fault - poor testing on the EVChargeSensor.  Update from Dev and should be ok now.

**Comment by ganzewin** [comment]
Works great now incl the Last Trip sensor. Thanks for your prompt response!

I will close this issue but please allow me to ask a question; 
How can i use the 'subvalue' of 'sensor.my_i_pace_ev_battery' in an automation? I want to use the value of "Charging" or "Charging Level" in order to notify myself when the car is NOT connected to the charger. 

![2020-04-30 23_03_42-HS12 - Home Assistant](https://user-images.githubusercontent.com/46644323/80759093-07e2fd00-8b37-11ea-8e35-562d2c1f0aae.png)

**Comment by msp1974** [comment]
You use the state_attr as a template value in the trigger.  Something like this

  `trigger:`
  `- platform: template`
 `   value_template: '{{state_attr("sensor.my_i-pace_ev_battery","charge level") < 50}}'`

or

  `trigger:`
  `- platform: template`
 `   value_template: '{{state_attr("sensor.my_i-pace_ev_battery","charging method") == 'Notconnected'}}'`

you can use the template section in the developer tools to test it out. Ie put this bit in the template section in developer tools and see if it evaluates to True (an automation trigger needs to be True or False).

`{{state_attr("sensor.my_i-pace_ev_battery","charging method") == 'Notconnected'}}`

**Comment by msp1974** [comment]
Sorry should also add the attribute name is case sensitive so will be "Charge Level" not "charge level" as I have written it in above examples.

EDIT: and the sensor name too!

**Comment by ganzewin** [comment]
Great! Works!
