### ISSUE TITLE
Error in Logbook: Task exception was never retrieved

### ISSUE THREAD

**Issue by ganzewin** [msp1974/homeassistant-jlrincontrol#20]
Log Details (ERROR)
Logger: homeassistant.core
Source: custom_components/jlrincontrol/services.py:19
First occurred: 9:17:45 AM (12 occurrences)
Last logged: 8:17:56 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/jlrincontrol/__init__.py", line 286, in async_health_update
    jlr_service = JLRService(self.hass, vehicle)
  File "/config/custom_components/jlrincontrol/services.py", line 19, in __init__
    self.attributes = self.vehicle.attributes
AttributeError: 'str' object has no attribute 'attributes'

**Comment by msp1974** [comment]
Im working on a fix for this. Its a bit more complicated than i thought. Give me a day or so and i'll update dev branch

**Comment by msp1974** [comment]
OK, I think I have got this sorted.  Can you please try the latest dev branch and let me know how you got on.  Thx

**Comment by ganzewin** [comment]
Sorry.. Now 2 different entries in the LOGS;

**Log Details (ERROR)**
Logger: homeassistant.components.sensor
Source: custom_components/jlrincontrol/__init__.py:424
Integration: Sensor (documentation, issues)
First occurred: 10:48:49 PM (1 occurrences)
Last logged: 10:48:49 PM

Error while setting up jlrincontrol platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 178, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/config/custom_components/jlrincontrol/sensor.py", line 50, in async_setup_platform
    devices.append(JLRVehicleRangeSensor(hass, discovery_info))
  File "/config/custom_components/jlrincontrol/sensor.py", line 230, in __init__
    self._units = self.get_distance_units()
  File "/config/custom_components/jlrincontrol/__init__.py", line 424, in get_distance_units
    return self.hass.config.units.length_unit
AttributeError: 'NoneType' object has no attribute 'config'



**Log Details (ERROR)**
Logger: homeassistant.components.template.sensor
Source: components/template/sensor.py:237
Integration: template (documentation, issues)
First occurred: 10:48:51 PM (1 occurrences)
Last logged: 10:48:51 PM

Could not render template my_ipace_charge_level: UndefinedError: 'mappingproxy object' has no attribute 'Charge Level'

**Comment by msp1974** [comment]
Sorry.  First issue was my fault.  Second issue is I think because it didn't load the sensor for the template sensor you created to show charge level.

Have added a fix to dev.

**Comment by msp1974** [comment]
This is now fixed in v1.3.  Is this working well for you now?

**Comment by msp1974** [comment]
Closing as believed fixed

**Comment by ganzewin** [comment]
Yes this works. I also changed to HACS which is working great too! Keep up the good work!
