### ISSUE TITLE
ModuleNotFoundError: No module named 'jlrpy'

### ISSUE THREAD

**Issue by cmatte** [msp1974/homeassistant-jlrincontrol#24]
Hi there,

It seems hass.io here is unable to import jlrpy and triggers the following.
Spotting a previous report here https://github.com/ardevd/jlrpy/issues/51#issuecomment-614324178 - raising an issue to track this.

> Error loading custom_components.jlrincontrol. Make sure all dependencies are installed
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 393, in _load_file
>     module = importlib.import_module(path)
>   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/config/custom_components/jlrincontrol/__init__.py", line 20, in <module>
>     import jlrpy
> ModuleNotFoundError: No module named 'jlrpy'

A simple pip install jlrpy pulled and correctly installed v1.3.3.

Thanks for your work on this - pretty exciting to see it :) 
Kind Regards,
Matteo.

**Comment by msp1974** [comment]
Matteo,  can I just ask how you installed this?  Was it as per the manual install instructions of via a custom repo in HACS?

I wonder if maybe the manual install instructions are wrong and I should recommend installing as custom repo via HACS (I have a PR outstanding to get into the HACS repo list).  I can't get it to fail via the HACS method but maybe Hass.io won't install the requirements itself.

Thanks Mark.

**Comment by cmatte** [comment]
Hi Mark,

Thanks for coming back to me. Yes, I have copy-pasted this folder manually yesterday and rebooted  after adding the config. I am running hass.io on a Synology device. For as much as I know, it was not even trying to install jlrpy. Also, HACS yesterday was erroring out while adding this repository due to lack of compliance with HACS standards.

The good news is today HACS worked and accepted the repository, instead! I have so uninstalled jlrpy manually from the docker container, re-installed the custom component (overwritten) via HACS, and HA has installed it automatically upon the reboot.
`2020-05-06 15:29:08 INFO (SyncWorker_11) [homeassistant.util.package] Attempting install of jlrpy==1.3.3
`

Hope this helps! Not sure if the manual install would not work with auto-installing required dependencies to be honest.

Thanks Mark.
Matteo.

**Comment by msp1974** [comment]
Closing as now intended to be installed via HACS and this works.
