### ISSUE TITLE
HA110 Base Class Change from *Device to *Entity 

### ISSUE THREAD

**Issue by MZorzy** [msp1974/homeassistant-jlrincontrol#25]
on other repo i see this change:
https://github.com/ReneNulschDE/mbapipy/commit/a05273b6c81e19d9bfa5d2de941d8b01d30a69db

LockDevice -> LockEntity
SwitchDevice -> SwitchEntity

**Comment by msp1974** [comment]
Thanks - updated in dev branch

**Comment by msp1974** [comment]
reopening as fails on HA109.  Need to add when HA110 released.

**Comment by msp1974** [comment]
Fixed in v2.0.0beta released today

**Comment by msp1974** [comment]
fixed in v2.0.1 new release.
