### ISSUE TITLE
Device tracker?

### ISSUE THREAD

**Issue by mariwing** [msp1974/homeassistant-jlrincontrol#31]
Hi and thanks for all your work on this. I own an I-PACE and this integration works great!

I see that you already pull in the last trip, would it be possible to add the destination_latitude and destination_longitude to a device tracker for the car? I am aware that a "real" device tracker is not possible since the JRL api don't provide real-time updates. It would still be of great use for me if there was a device tracker for the car. For example; if the car is parked at home and has less than 50% battery in the evening; send a notification. Another use case; I sometimes take the car to work and other times I use public transport. So if the car is in the work zone at 16:00 I could get an update for estimated travel time with my car. And if not; provide me with latest information about the public transport.

**Comment by msp1974** [comment]
This does have a device tracker. Can you check it is there or check that there is not an error in the logs trying to load it.

**Comment by mariwing** [comment]
I thought that I saw in the documentation that it should have a device tracker. Unfortunately I am unable to find it when I look at the device trackers entites in the developer console. I don't find anything in the logs either, the only message I can find is the warning of running a custom component and missing pin for door locking.

I have a sensor "last_trip" wich shows departure and arrival. Is this the one you are thinking of or should I have had an explicit device_tracker enitity as well? If so; I could probably change the loglevel and see if any more information gets logged.

**Comment by msp1974** [comment]
You should have an explicit device tracker in addition to the last trip sensor. Turn on debug logging as see if it gets created. The other thing i think thwt can happen is that you have your HA set not to track new devices. Cant remember how this is set but i think something to do with known devices.yaml.

**Comment by MZorzy** [comment]
there is **device_tracker**._mycar_   with latitude and latitude. 
and work with **Zones** if you set up it under Dashboarr/Zone.

can done Automation llike "if the car is in the work zone at 16:00 I could "  BUT it's not real-time so can be some issue.
maybe with trigger time 15:55 call service jlrincontrol.update_health_status for the car
then trigger time 15:59, and then check time&position (conditions: State/device_tracker.mycar/"zona name") etc.

**Comment by msp1974** [comment]
@mariwing did you get this working.  Happy to help you resolve if needed.

**Comment by mariwing** [comment]
Thank you both @MZorzy and @msp1974. The thing that fixed it was to go to known_devices.yaml and find the entry and then set track: true. You where correct that I had default = false to track new devices.

**Comment by MZorzy** [comment]
look like tracker is changed from **device_tracker.rrs** to **device_tracker.rrs_device_tracker**
