### ISSUE TITLE
Change State for ev_battery sensor?

### ISSUE THREAD

**Issue by mariwing** [msp1974/homeassistant-jlrincontrol#32]
I own an I-PACE and it is great that you have an ev_battery sensor :-) I would suggest that you change the "State" attribute to show "State of charge" or "Charge level" as you have called the attribute. I don't think the message that is chosen today is what most people with an electric car would like to show as default value for the sensor on their dashboard. I suspect that most people would like to have the remaining battery shown.

**Comment by msp1974** [comment]
I dont have an iPace (yet) so the EV sensor was a bit of a guess. Any guidance on how best to make this work is welcome. I also thought about having a battery sensor (like battery sensors for phones etc) that would show this. Do you think this is a good idea instead of making this sensor show battery as default state?

I also dont know if the attributes on the ev sensor work well or not. Any feedback on changes/enhancements welcome.

**Comment by mariwing** [comment]
I think a battery sensor like phone have is a good idea and it would fit my purpose very well (for example an alert to remember to plug in my veichle. If you could also directly in this battery sensor include if it is charing or not (example below the attribute battery_status) that would be awesome. 

sensor.marius_11_battery_state_2 | 50 | attribution: Data provided by Apple iCloud account_fetch_interval: 30 device_name: iPhone 11 Pro Max device_status: online owner_fullname: Marius Wingerei battery_status: NotCharging battery: 50 low_power_mode: false unit_of_measurement: % friendly_name: Marius 11 battery state icon: mdi:battery-50 device_class: battery
-- | -- | --

I will think a little more about the other attributes on the ev_battery sensor and give you some more feedback on what makes sense.

Thank you for quick reply and your interest in developing this and helping me out!

**Comment by mariwing** [comment]
![image](https://user-images.githubusercontent.com/5949497/82330336-ff1d7280-99e2-11ea-8706-aa1538435745.png)

This is how the sensor for the battery looks like when the car is plugged in and charging. I have some comments:

- "No Message" seems to mean that the car is not charging. The other messages I have seen are "Initalizing" (when plugged in, shown until charging starts to charge) and "Charging" (as in my screenshot).
- Attribute "Charging" is Unknown. I don't know where it get's it value from. Maybe it should be a boolan true/false based on "Message" where if Message=Charging it should be true, otherwise false?
- Attribute "Charge Level" I think should be "State of Charge" since it seems to show the battery percentage. It could also be named "Battery level" which is the term used in the range sensor
- Charging mode seems to be a constant. In my case I dont have any scheduled (or timed) charging setup
- Charge Type is unknown, both to me and the sensor ;-)
- Is plugged In: It is strange that since the car is charging and the Charging Method is Wired that the sensor don't know if it is plugged in or not. So if this is some value from the api it could just be removed I think because it doesn't seem to contain valuable data
- Kwh Used Since Last Charge seems to display something completely different. It increases while charging but it increases way too fast to be kWh I think. And when not charging the value don't increase so it doesn't seem to show consumption since last charge.

If you have any further questions regarding this me and my I-PACE are happy to assist. I am super-happy to see this integration beeing actively developed for Home Assistant. Appreciate it a lot!

**Comment by msp1974** [comment]
This is great feedback thanks.  Just released v1.3.1 to fix a bug when position or trip data not being returned from JLR servers raised by MZorzy.  Will now work on these improvements and put into dev branch for you to tell me what you think.  Will let you know when available to test.

**Comment by msp1974** [comment]
OK, I have added an update to the dev branch, if you could test and give me feedback on
1) Does this actually work correctly?
2) Is it what you had in mind to show?

I have currently created this as a new Battery sensor, which you will need to add to Lovelace after restart of HA.

**Comment by msp1974** [comment]
@mariwing - have you had chance to test this yet?

**Comment by mariwing** [comment]
Checking this out this afternoon. There is a bug on line 371 in sensor.py with regards to str and int. 

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 186, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 295, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 384, in _async_add_entity
    original_icon=entity.icon,
  File "/config/custom_components/jlrincontrol/sensor.py", line 372, in icon
    self._charging_state,
  File "/usr/src/homeassistant/homeassistant/helpers/icon.py", line 16, in icon_for_battery_level
    elif battery_level <= 5:
TypeError: '<=' not supported between instances of 'str' and 'int'

I fixed it by wrapping the line with a int() but not sure if this is the best solution (I am no Python developer):  int(self._vehicle.status.get("EV_STATE_OF_CHARGE", 0))

With that in place, the sensor loads and looks good. Currently my car is at 99% and not charging but it seems that the information given is better. The only thing is that Last Charge Energy is not kWh. The attributes shows 283 for my car now and since the battery is approximately 90 kWh it couldn't possible have added 283 kWh in the last charging session :-) I think I charged from around 70% and to full so my quess is that this should be 28.3 kWh which makes sense (30% of 90 is 27).

I like the two attributes for charging time (km/h and %) but the most usefull (at least for people used to driving electric cars) would be to show the charge rate as kW. As far as I know this is not available from the API but it could be estimated by taking the % added per hour and multiply it with the usable battery size. There is no official number on available/usable battery size but i think that using 90 as the basis for this calculation will give a good enough number. The official Jaguar app shows 4% added per hour when I charge at home and since I know that I can charge with a maximum of 3.6 kW at my home charger and 4% * 90 gives 3.6 I think that this is fairly accurate.

Thank you once again for your work on this!

**Comment by msp1974** [comment]
Sorry been quiet for a couple of days, been working hard on adding a config flow setup to this integration.

Along with the config flow changes, I have updated the dev branch to fix the bug (your way of fixing is absolutely correct) and change the Last Charge Energy to be /10.

For the rate of charge in kW, I am not sure setting a fixed value of 90 is a good idea, as other models will come out with diff batteries.  However, there does seem to be a couple of status attributes come back from the car as below (these are from someone elses iPace).  If these are correct it shows the battery capacity and the degredation over time.  This iPace had about 30K Km on it.  Although 80kW seems very low.  Can you look at yours and see what it says for these 2 params.

"EV_RANGE_VSC_INITIAL_HV_BATT_ENERGYx100" | 102.35,
-- | --
"EV_RANGE_VSC_REVISED_HV_BATT_ENERGYx100" | 80.05,

Thanks
Mark

**Comment by mariwing** [comment]
Great that you look more into this. For the record; my car has these values:

"EV_RANGE_VSC_INITIAL_HV_BATT_ENERGYx100" | 102.35
-- | --
"EV_RANGE_VSC_REVISED_HV_BATT_ENERGYx100" | 68.4

I know from following the "debate" on a Norwegian I-PACE Owner Facebook group and also by looking at the alternative Jaguar app for Android (Wattcat) which uses the same reverse-enginered api as you do that finding the charge rate is very hard. The developer of the app gives an explanation in post #2 in this thread: https://www.ipaceforums.co.uk/viewtopic.php?t=2959 why the two numbers/attributes you asked for can not be used for battery estimates (anymore). 

Also; if you read this post https://www.ipaceforums.co.uk/viewtopic.php?t=1820 you can see from the release notes of Wattcat that it now shows charging rate. Unfortunately the source code for Wattcat is not open AFAIK so I don't know how he computes it. My main phone is an iPhone but I also have a spare Android so I will install latest version of Wattcat and start to charge my car and see what kind of information it shows.

An idea since it seems that the api don't reveal neither the correct battery "size" nor the charge rate in watts (which is what I wished for in the first place) is that the battery size to use for computations could be a user input? Since you are now working at a config flow setup and I guess you have mastered it the value could be added as part of the setup?

**Comment by mariwing** [comment]
Just installed version 2.0.1 and the new battery sensor is awesome! Thank you so much for working on this :-)

**Comment by msp1974** [comment]
Great and thanks.  Glad you like it.

I was thinking more about your request to look at rate of charge.  I'm not sure whether it is a good idea to put this as a sensor/sensor attribute doe to the requirement to set the battery capacity for it to work and the fact that it is really an approximation rather than accurate data returned from car.  However, if you wanted to do this you could create a template sensor for your personal config which I can help you with if you want.
