### ISSUE TITLE
[minor] please round 2 pressure tyre

### ISSUE THREAD

**Issue by MZorzy** [msp1974/homeassistant-jlrincontrol#34]
may you round 2 tyre pressure, so have like 2,61bar and not 2,6bar

ref: https://github.com/msp1974/homeassistant-jlrincontrol/blob/1f9dbbb7d6c5c0fc2b44694fb10669413caac8d5/custom_components/jlrincontrol/sensor.py#L152
and line 160.

tnx

**Comment by msp1974** [comment]
Will add to next release

**Comment by msp1974** [comment]
v2.0.0beta released via HACs which fixes this issue.  Please can you test and let me know.

**Comment by MZorzy** [comment]
good. tnx
