### ISSUE TITLE
Incorrect tyre pressure

### ISSUE THREAD

**Issue by stefan-west1** [msp1974/homeassistant-jlrincontrol#35]
Tyre pressure set to psi - showing as 475psi currently. Not entirely sure why though

![Annotation 2020-05-26 221504](https://user-images.githubusercontent.com/65961309/82951047-62d50c00-9f9e-11ea-98e0-2530522d9b15.png)

**Comment by msp1974** [comment]
Have seen similar on  my XF. Seems, in my case, if the car is sat for a while that you get erroneous high readings for tyre pressure.  In my case it also shows no sensors for status. Sometimes it corrects on its own, sometimes after a drive.  Mine is currently showing same reading as not driven it for a week or so.

**Comment by stefan-west1** [comment]
That could well be the problem then. In which case ignore me and I'll just close the issue!
