### ISSUE TITLE
Installed successfully but the card doesn't show up under overview of hassio

### ISSUE THREAD

**Issue by kpejman** [msp1974/homeassistant-jlrincontrol#44]
Installed successfully but the card doesn't show up under overview of hassio.
the sample image section I can't see it in hassio but I can see all sensors pull the data successfully.

**Comment by msp1974** [comment]
Please see the readme file with link to recipes of how to create these.

https://github.com/msp1974/homeassistant-jlrincontrol/blob/master/Recipes.md
