### ISSUE TITLE
Unable to send commands after activating 

### ISSUE THREAD

**Issue by pruvi9019** [msp1974/homeassistant-jlrincontrol#46]
Hi, after checking show all data sensor box none of the commands work. Also, information shown from default sensors are also wrong. This part seems to be broken even before checking all data sensor box.

Failed to call service lock/lock. 'NoneType' object is not iterable

**Comment by msp1974** [comment]
Yes, aware of this. The dev repo has the fix for this but not had chance to deploy to release version. Will try and do very soon.

**Comment by msp1974** [comment]
If you want to fix it yourself until a release is available, line 100 in sensor.py needs amending from
attributes = self._vehicle.attributes
To
attributes = self._vehicle.attributes.copy()

**Comment by pruvi9019** [comment]
I updated the as mentioned above however still receiving the same error. 

 'Failed to call service lock/lock. 'NoneType' object is not iterable'

**Comment by msp1974** [comment]
@pruvi9019   I have now released version 2.1.1 that should fix this error.  May take a few hours for your HACs to see update.  Give it a try and let me know if this resolves.  I have tested on my install and this does not error with all data sensor enabled.

**Comment by msp1974** [comment]
Did this fix your issue @pruvi9019 ?

**Comment by msp1974** [comment]
Closing issue as believed fixed.
