### ISSUE TITLE
sensor.xxxx_battery doesn't show up anymore

### ISSUE THREAD

**Issue by ganzewin** [msp1974/homeassistant-jlrincontrol#50]
My integration worked for months without this issue and now suddenly the sensor.xxxx_battery doesn't show up anymore while all the other sensors are there and the integration seems to work. Something changed on the JLR side??

Logger: homeassistant.components.sensor
Source: custom_components/jlrincontrol/sensor.py:473
Integration: Sensor (documentation, issues)
First occurred: 5:41:57 PM (2 occurrences)
Last logged: 5:41:57 PM

Error adding entities for domain sensor with platform jlrincontrol
Error while setting up jlrincontrol platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 316, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 531, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 296, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 323, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/jlrincontrol/sensor.py", line 473, in device_state_attributes
    int(s.get("EV_ENERGY_CONSUMED_LAST_CHARGE_KWH", 0)) / 10, 1
ValueError: invalid literal for int() with base 10: 'UNKNOWN'

**Comment by msp1974** [comment]
Looks like the jlr server is returning a value of UNKNOWN instead of a numeric value.  Not sure if this is a temp glitch or a change to the api.If you enabke the all sensor from the config options and see if tgere is a different sensor vakue showing.  Post sensor calues here also as may help diagnose.  Dont have an EV to test myself.MarkSent from my Galaxy

**Comment by ganzewin** [comment]
In the ALL sensor the vaue shows UNKNOWN. I will check if it is a temp-glitch and let you know when the situation changes. 

  evEnergyConsumedLastChargeKwh: UNKNOWN



attributes:
  bodyType: 5 Door Estate
  carLocatorMapDistance: null
  constructionDate: null
  country: NLD
  deliveryDate: null
  deviceState: JLR_PROVISIONED_MODE
  engineCode: Electric
  exteriorCode: Black
  exteriorColorName: Black
  fuelTankVolume: null
  fuelType: Electric
  gearboxCode: Automatic
  grossWeight: 2211
  interiorCode: null
  interiorColorName: null
  modelYear: 2019
  nickname: My i-Pace
  numberOfDoors: 5
  registrationNumber: XXXXXXXXX
  roofType: NOT_OPENABLE
  seatsQuantity: 5
  subscriptionStartDate: null
  subscriptionStopDate: null
  subscriptionType: null
  telematicsDevice:
    serialNumber: 809VILZ664096
    imei: null
  timeFullyAccessible: null
  timePartiallyAccessible: null
  tyreDimensionCode: null
  tyreInflationPressureHeavyCode: null
  tyreInflationPressureLightCode: null
  vehicleBrand: Jaguar
  vehicleType: I-PACE
  vehicleTypeCode: X590
status:
  armRestSecondRowInhibition: UNKNOWN
  armRestSecondRowStatus: UNKNOWN
  batteryStatus: BATTERY_1_1
  batteryVoltage: '13.5'
  brakeFluidWarn: NORMAL
  brazilEventMode: 'FALSE'
  climateStatusFfhRemainingRuntime: '0'
  climateStatusOperatingStatus: 'OFF'
  climateStatusRemainingRuntime: '30'
  climateStatusTimer1Day: '0'
  climateStatusTimer1Hour: '0'
  climateStatusTimer1Minute: '0'
  climateStatusTimer1Month: '0'
  climateStatusTimer2Day: '0'
  climateStatusTimer2Hour: '0'
  climateStatusTimer2Minute: '0'
  climateStatusTimer2Month: '0'
  climateStatusTimerActivationStatus: 'FALSE'
  climateStatusVentingTime: '30'
  distanceToEmptyFuel: '0'
  doorBootLockStatus: LOCKED
  doorBootPosition: CLOSED
  doorEngineHoodLockStatus: LOCKED
  doorEngineHoodPosition: CLOSED
  doorFrontLeftLockStatus: LOCKED
  doorFrontLeftPosition: CLOSED
  doorFrontRightLockStatus: LOCKED
  doorFrontRightPosition: CLOSED
  doorIsAllDoorsLocked: 'TRUE'
  doorIsBootLocked: 'TRUE'
  doorRearLeftLockStatus: LOCKED
  doorRearLeftPosition: CLOSED
  doorRearRightLockStatus: LOCKED
  doorRearRightPosition: CLOSED
  drvSeatSecondRowInhibition: UNKNOWN
  drvSeatSecondRowStatus: UNKNOWN
  drvSeatThirdRowInhibition: UNKNOWN
  drvSeatThirdRowStatus: UNKNOWN
  engCoolantLevelWarn: NORMAL
  engineBlock: NORMAL_UNBLOCKED
  engineCoolantTemp: '-60'
  evBatteryPreconditioningStatus: UNKNOWN
  evChargeNowSetting: FORCE_ON
  evChargeType: UNKNOWN
  evChargingMethod: NOTCONNECTED
  evChargingModeChoice: TIMEDCHARGINGNOTACTIVE
  evChargingRateKmPerHour: '6'
  evChargingRateMilesPerHour: '4'
  evChargingRateSocPerHour: UNKNOWN
  evChargingStatus: No Message
  evEnergyConsumedLastChargeKwh: UNKNOWN
  evIsCharging: UNKNOWN
  evIsPluggedIn: UNKNOWN
  evIsPreconditioning: UNKNOWN
  evMinutesToBulkCharged: '22'
  evMinutesToFullyCharged: '22'
  evNextDepartureTimerDateDay: '1'
  evNextDepartureTimerDateMonth: '1'
  evNextDepartureTimerDateYear: '2000'
  evNextDepartureTimerIsSet: 'true'
  evNextDepartureTimerTimeHour: '0'
  evNextDepartureTimerTimeMinute: '0'
  evOneOffMaxSocChargeSettingChoice: CLEAR
  evOneOffMaxValue: '-1'
  evPermanentMaxSocChargeSettingChoice: CLEAR
  evPhevRangeCombinedKm: '-1'
  evPhevRangeCombinedMiles: '-1'
  evPreconditionFuelFiredHeaterSetting: DISABLED
  evPreconditionOperatingStatus: 'OFF'
  evPreconditionPrioritySetting: PRIORITIZE_COMFORT
  evPreconditionRemainingRuntimeMinutes: '0'
  evPreconditioningMode: INACTIVE
  evRangeComfortx10: '0.0'
  evRangeEcox10: '0.0'
  evRangeGetMeHomex10: '0.0'
  evRangeOnBatteryKm: '359'
  evRangeOnBatteryMiles: '223'
  evRangePredictStatus: DISPLAY_RANGE
  evRangeVscHvBatteryConsumptionSpd1: '100'
  evRangeVscHvBatteryConsumptionSpd2: '100'
  evRangeVscHvBatteryConsumptionSpd3: '100'
  evRangeVscHvBatteryConsumptionSpd4: '100'
  evRangeVscHvBatteryConsumptionSpd5: '100'
  evRangeVscHvBatteryConsumptionSpd6: '100'
  evRangeVscHvBatteryConsumptionSpd7: '100'
  evRangeVscHvEnergyAscentx10: '0.0'
  evRangeVscHvEnergyDescentx10: '0.0'
  evRangeVscHvEnergyTimePenx100: '0.0'
  evRangeVscInitialHvBattEnergyx100: '0.0'
  evRangeVscRangeMapRefactrComf: '0'
  evRangeVscRangeMapRefactrEco: '0'
  evRangeVscRangeMapRefactrGmh: '0'
  evRangeVscRegenEnergyAvailablex100: '0.0'
  evRangeVscRegenEnergyFactor: '0'
  evRangeVscRevisedHvBattEnergyx100: '0.0'
  evRangeVscVehAccelFactor: '100'
  evStateOfCharge: '100'
  extBulbStatusLeftTurnAny: '0'
  extKilometersToService: '32000'
  extOilLevelWarn: NORMAL
  fuelLevelPerc: '0'
  isCabOpen: 'FALSE'
  isCrashSituation: 'FALSE'
  isHeadLightsOn: UNKNOWN
  isPanicAlarmTriggered: UNKNOWN
  isSunroofOpen: 'FALSE'
  lastupdatedtime: '2021-01-02T18:20:12+0000'
  latestCompleteConfigUpdate: '2020-02-19T07:06:35+0000'
  odometer: '72594000'
  odometerMeter: '72594000'
  odometerMeterResolution: 'true'
  odometerMiles: '45108'
  odometerMilesResolution: 'false'
  pasSeatFirstRowInhibition: UNKNOWN
  pasSeatFirstRowStatus: UNKNOWN
  pasSeatSecondRowInhibition: UNKNOWN
  pasSeatSecondRowStatus: UNKNOWN
  pasSeatThirdRowInhibition: UNKNOWN
  pasSeatThirdRowStatus: UNKNOWN
  privacySwitch: 'FALSE'
  serviceModeStart: '2020-01-30T13:01:26+0000'
  serviceModeStop: '2020-01-30T18:01:26+0000'
  srsStatus: SRS_NOT_DEPLOYED
  theftAlarmStatus: ALARM_ARMED
  transportModeStart: '1970-01-01T00:00:00+0000'
  transportModeStop: '1970-01-01T00:00:00+0000'
  tuActivationStatus: PROVISIONED
  tuStatusButtons: FUNCTIONING
  tuStatusCan: UNCERTAIN
  tuStatusConfigVersion: '26'
  tuStatusCrashInput: UNCERTAIN
  tuStatusDaysSinceGnssFix: '3'
  tuStatusExtHandsfree: BROKEN
  tuStatusExtPower: FUNCTIONING
  tuStatusGnss: FUNCTIONING
  tuStatusGnssAntenna: FUNCTIONING
  tuStatusGsmExtAntenna: FUNCTIONING
  tuStatusGsmModem: FUNCTIONING
  tuStatusHandset: UNCERTAIN
  tuStatusHwVersion: J8A2-70719-CG
  tuStatusImei: '358492072431478'
  tuStatusIntPower: FUNCTIONING
  tuStatusIntRtc: FUNCTIONING
  tuStatusMic: FUNCTIONING
  tuStatusMobilePhoneConnected: 'TRUE'
  tuStatusPower: MAIN_BATTERY
  tuStatusPrimaryChargePercent: '90'
  tuStatusPrimaryVolt: '4.1000000000000005'
  tuStatusSecondaryVolt: '0.0'
  tuStatusSerialNumber: 809VILZ664096
  tuStatusSleepCyclesStartTime: '2021-01-01T18:58:44.000Z'
  tuStatusSpeaker: FUNCTIONING
  tuStatusSwVersionConfig: J7A3-70713-AT
  tuStatusSwVersionMain: J8A2-70712-AT
  tuStatusSwVersionSecondary: J8A2-70712-BT
  tuStatusUsesExternalGnss: 'FALSE'
  tyrePressureFrontLeft: '1000'
  tyrePressureFrontRight: '1000'
  tyrePressureRearLeft: '1000'
  tyrePressureRearRight: '1000'
  tyreStatusFrontLeft: NORMAL
  tyreStatusFrontRight: NORMAL
  tyreStatusRearLeft: NORMAL
  tyreStatusRearRight: NORMAL
  vehicleStateType: KEY_REMOVED
  washerFluidWarn: NORMAL
  windowFrontLeftStatus: CLOSED
  windowFrontRightStatus: CLOSED
  windowRearLeftStatus: CLOSED
  windowRearRightStatus: CLOSED
position:
  calculatedPosition: null
  position:
    longitude: XX.XXX
    latitude: XX.XXX
    timestamp: '2021-01-01T18:58:44+0000'
    speed: 0
    heading: 0
    positionQuality: null
friendly_name: CAR Jaguar All Info
icon: 'mdi:cloud'
assumed_state: true

**Comment by ganzewin** [comment]
Hi Mark, it was a temp issue. I decided to take a drive and since then the value is correct and the sensor appeared again (as HASS was checking the status every 5 minutes (scaninterval)). Thanks for quick response and i will close the issue.
