### ISSUE TITLE
PIN get changed to 324 automatically in Lovelace code editor

### ISSUE THREAD

**Issue by bergetun** [msp1974/homeassistant-jlrincontrol#51]
I am experiencing a strange problem when trying to add a Lock door card to lovelace.  

If i add this card with the pin code 0000 and click save , it automatically changes back to the pin code 324 next time i open the code editor for that card.   I dont know if this is a HA problem or jlrincontroll addon problem, but i have only experinced with this addon.

`entity: sensor.the_jag_info
hold_action:
  action: more-info
name: Update My Car
show_icon: true
show_name: true
tap_action:
  action: call-service
  service: jlrincontrol.update_health_status
  service_data:
    entity_id: sensor.my_car_info
    pin: 0000
type: button`

**Comment by msp1974** [comment]
I have not seen this issue before.  Howecer, you can set the pin im the integration options.  Have you got the same pin set in there?Sent from my Galaxy

**Comment by bergetun** [comment]
I had to from my original code 0504 to something else, then it worked.  It seems like it didnt like the code 0504  ?  
It doesnt like when the pin starts with 0 it seems like.

**Comment by msp1974** [comment]
I think then that this maybe we are storing the pin as a number so it is stripping leading 0s. Will leave this issue open to fix for next release.Sent from my Galaxy
-------- Original message --------From: bergetun <notifications@github.com> Date: 03/02/2021  18:07  (GMT+00:00) To: msp1974/homeassistant-jlrincontrol <homeassistant-jlrincontrol@noreply.github.com> Cc: Mark Parker <msparker@sky.com>, Comment <comment@noreply.github.com> Subject: Re: [msp1974/homeassistant-jlrincontrol] PIN get changed to 324 automatically in Lovelace code editor (#51) 
I had to from my original code 0504 to something else, then it worked.  It seems like it didnt like the code 0504  ?
It doesnt like when the pin starts with 0 it seems like.

**Comment by sdeagh** [comment]
Just to add, I have experienced the same issue with my pin being reset to 200 in the UI. My PIN also starts with a 0 but the last 3 digits are not 200 so not as simple as dropping the leading 0 I'm afraid

**Comment by msp1974** [comment]
I know this is an old issue now and I think was fixed some time ago in 2.1.4 but is anyone on this issue still having the problem or can we close this?  FYI - there will be a v2.2.0 release in the next week or so (just release v2.2.0beta for testing as a pre-release).

**Comment by msp1974** [comment]
Closing this issue as no feedback that it is not working.
