### ISSUE TITLE
Battery voltage for "start" battery is wrong on I-Pace 

### ISSUE THREAD

**Issue by bergetun** [msp1974/homeassistant-jlrincontrol#52]
First of all. Thanks for a GREAT program.. Love it. 

When trying to get the Voltage for the "start" battery i get 16.5 volt with this plugin.  
On the iphone program WhatCatt i get 12.5v 

This is the code i am using. : 

`Jaguar voltage: 
{{ (state_attr('sensor.the_jag_all_info', 'status')).batteryVoltage }}`

Edit: Never mind, WattCat app also gives the same value, so it is not this plugins fault.

**Comment by msp1974** [comment]
Closing as integration is reporting correctly from jlr servers.
