### ISSUE TITLE
HA Warning - No 'version' key in the manifest file

### ISSUE THREAD

**Issue by gsksim** [msp1974/homeassistant-jlrincontrol#53]
New warning in Home Assistant when loaded.
No 'version' key in the manifest file for custom integration 'jlrincontrol'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'jlrincontrol'

**Comment by msp1974** [comment]
Sorry been quiet recently. I will provide an updated version to fix this over next few days.
