### ISSUE TITLE
I changed my InControl password. How do I update Home Assistant?

### ISSUE THREAD

**Issue by rozza-m** [msp1974/homeassistant-jlrincontrol#56]
As title, I can't find any guidance or means to update my password.

It's not in configuration.yaml and the option isn't there in the web interface of HA. How do I do it?

**Comment by MZorzy** [comment]
i think that the "fast way" is remove from hacs then readd (as integration)

**Comment by rozza-m** [comment]
will that lose all of my connected stuff?

**Comment by msp1974** [comment]
You can amend it by editing the file in the .storage directory in your config directory, edit the core.config_entires file. Find the entity with domain name of jlrincontrol and you will see the username and password entries. Amend your password in here, save the file and restart HA.  This is a bit fiddly but saves you having to delete and reinstall.

**Comment by msp1974** [comment]
@rozza-m did you manage to sort this?

**Comment by rozza-m** [comment]
Yes, following your instructions worked, thank you! @msp1974 Is it reasonable to open a ticket to request that there's a supported mechanism for password changes rather than digging into these files?

**Comment by msp1974** [comment]
I think it's a limitation of HA but I could be wrong.  If you know of any integrations that allow you to do this let me know and I will see about adding.Sent from my Galaxy
