### ISSUE TITLE
Intergration -> Configuration Missing

### ISSUE THREAD

**Issue by jeremy-mattern** [msp1974/homeassistant-jlrincontrol#59]
Not sure what I'm doing wrong, but I've installed this twice in HACS and cant find the configuration. I can not add it under Configuration -> Integrations because its not on the list.

**Comment by msp1974** [comment]
Ive seen a number of times before that you need to do a shift F5 refresh of your browser as it caches the list.  This wil force it to load the page without loading any cached content.Sent from my Galaxy

**Comment by msp1974** [comment]
@jeremy-mattern I presume you resolved this.  Will close but let me know if not.  Thx
