### ISSUE TITLE
Land Rover location not real time

### ISSUE THREAD

**Issue by gavinpbennett** [msp1974/homeassistant-jlrincontrol#63]
I have this integration working very well. But have one nuisance of an issue. I have the health status updating every hour, and am able to manually request the update with a button. The issue is that the car location does not seem to update to its real time position. It still shows as the last location that the car was switched off. However, when using the Land Rover InControl app, I can see the location updates in real time. This indicates that the InControl system is getting real time updates.
My question really is how do I get the car location to update using this integration, to its current real time location? As per the screenshots, the LR app shows me on the motorway, while at the same time, 2 mins after a manual health update, HA shows me as at home (which is nowhere near where I was)
![ha](https://user-images.githubusercontent.com/25515563/149229473-d1d7fe4b-2b16-4734-ad90-85e5e2b4923e.jpg)
![lr](https://user-images.githubusercontent.com/25515563/149229490-c0abde24-13a9-446c-a161-a483cd9ef95e.jpg)
.

**Comment by ismarslomic** [comment]
@gavinpbennett did you solve this issue? I have identical question in #82

**Comment by gavinpbennett** [comment]
@ismarslomic No, I have just learned to live with it, sadly.
