### ISSUE TITLE
Not showing in integrations 

### ISSUE THREAD

**Issue by McFarTech** [msp1974/homeassistant-jlrincontrol#65]
Hi. 

I am running the latest version of HA. I have installed via HACS but when i try to add / configure via integrations i dont see it listed. Anything i can check or do?

**Comment by McFarTech** [comment]
Not to worry. seemed it was cache issue.

**Comment by msp1974** [comment]
This seems to be a common HA issue that it caches the list so you need to do a shift F5 refresh on your browser to refresh the page not using cache and it should appear.Sent from my Galaxy
-------- Original message --------From: McFarTech ***@***.***> Date: 08/02/2022  20:35  (GMT+00:00) To: msp1974/homeassistant-jlrincontrol ***@***.***> Cc: Subscribed ***@***.***> Subject: [msp1974/homeassistant-jlrincontrol] Not showing in integrations  (Issue #65) 
Hi.
I am running the latest version of HA. I have installed via HACS but when i try to add / configure via integrations i dont see it listed. Anything i can check or do?
