### ISSUE TITLE
Reset Password

### ISSUE THREAD

**Issue by RcRaCk2k** [msp1974/homeassistant-jlrincontrol#68]
Hi,

how can i replace my login credenticals for incontrol?

I had to change my password and since then hassio was not able anymore to update data.

**Comment by msp1974** [comment]
You need to remove and re-add.  It's a bit of a HA issue I'm afraid. However, when you re-add the entity names should stay the same so all your dashboard stuff should come back (unless you renamed them).

**Comment by RcRaCk2k** [comment]
Thank you. I had to rename all entity-names because the cars name was changed in the incontrol app. But it only tooks about 2 minutes, that is okay for me ^^
