### ISSUE TITLE
Missing Attributes

### ISSUE THREAD

**Issue by BNWEIN** [msp1974/homeassistant-jlrincontrol#69]
Good Morning.

I have this setup and working for a few of the easier items (i can turn the car on, check the status of the Windows, Alarm etc), however none of the additional attributes seem to show up. For example I cannot see any of the following: 

Distance to Service

No errors that i can see in the log?  Even the "Show all data Sensor" has no attributes?

**Comment by msp1974** [comment]
Can you please provide more details such as what car you have, version of HA.  Can you also enable data debug in the config options and also turn on debug for this integration in configuration.yaml and provide me the output.

**Comment by BNWEIN** [comment]
Sorry of course! 

Landrover Discovery 2020/2021 model
Home Assistant 2022.4.7

**Edited, i just realised this debug log contains some sensitive information, i have redacted and will re-upload

**Comment by BNWEIN** [comment]
Re-uploading log and removed the "Old Car" from there to avoid confusion

[debug log.txt](https://github.com/msp1974/homeassistant-jlrincontrol/files/8561305/debug.log.txt)

**Comment by msp1974** [comment]
Hmm, it looks like they should be there and it is creating all the sensors as it should.  I can see that you have 2 cars on your account.  Do either of them show the attributes?  This integration should work with having multiple cars on an account but wonder of that is where the issue may be.  Can you show me some screenshots for the following:

1) The integration config device screen for both your cars (obfuscate the reg) as below:
![image](https://user-images.githubusercontent.com/11211952/165280177-9b915928-4b94-4af0-86b0-666b2fa22cf0.png)

2) The attributes screen for the all info sensor (for both)(obfuscate anything sensitive).
![image](https://user-images.githubusercontent.com/11211952/165280771-06850bba-29ba-4007-b7da-b41f9f7b220c.png)

I have blanked a lot out as it is not my data but show me as much as you can.  Need to see if this is some sort of mixup between your 2 cars.

As a note (but might be worth trying) - see issue #66 .  There is an updated version in the dev branch that if you know how to clone and use in HA might be worth testing.  There are a number of changes in this and I am waiting to get some testing on non PHEV vehicles before releasing.  It also has better debugging that may help find the issue.  No problem if you can't, we should be able to work out the problem in this version with a bit of trial and error.

**Comment by BNWEIN** [comment]
Firstly thanks for all the responses so far! Appreciate the great support!

OK so a few things

1: I only actually have 1 car. The other car is an old car that we no longer own. I have just logged into the Landrover InControl website and deleted that old car.  I have deleted the integration, rebooted, and re-installed the integration.  Still same issue (but now the old car is gone!).

2: Screen shot 1
![image](https://user-images.githubusercontent.com/28929905/165283143-180d87dc-0ee5-4471-b798-4bdbe6f3dc42.png)

3: Screen shot 2 (missing the attributes!)
![image](https://user-images.githubusercontent.com/28929905/165283300-76564061-3b41-4b1b-8c34-22818bb78b39.png)

Not entirely sure how I clone and use the beta version I am afraid.

**Comment by msp1974** [comment]
Ah - light bulb moment.  

Sorry I have not done much on this integration for some time until recently and looks like the current released version is an old one (2.1.3) that does not work with HA after 2021.12 (ish) when they changed the name of the attributes.  I will release a new version shortly as a beta version (this will be the one in the dev branch).  It might have some errors but think it works ok (as I said was looking for a non PHEV to do final testing with).  I will let you know when done and then you will need to enable show beta versions on the integration in HACS - weirdly from the redownload option as below.  It will be 2.2.0beta.

![image](https://user-images.githubusercontent.com/11211952/165287984-171a92fc-e7d5-4a61-96a8-cdc491065412.png)

**Comment by msp1974** [comment]
OK just released.  If this has errors, v2.1.4 is also a beta release that i know a number of people have been using ok.  You can try that version too.

**Comment by BNWEIN** [comment]
2.2.0 has indeed fixed the issue! 

Thank you.

**Comment by msp1974** [comment]
Great,  Can you let me know how you get on and add any issues to #66.  If it seems all ok, I will release this as an official version at the weekend.

Thanks and glad we got it sorted.
