### ISSUE TITLE
Question rather than an issue!  Map

### ISSUE THREAD

**Issue by BNWEIN** [msp1974/homeassistant-jlrincontrol#70]
Hi Mike

I wish Github hadnt removed the ability to message someone!  This may not be the best place for me to ask this, but I am looking for a way to use a MAP card along side the "Position" attribute under the "All_info" sensor.  Do you know how i can do this?

**Comment by msp1974** [comment]
You should be able to use the device tracker entity to display your car on the main HA map or map card.  I know that you only get geo location updates when the engine is switched off and therefore you can't really track where it is/has been when moving.

Hope that helps,
Mark

**Comment by BNWEIN** [comment]
I don’t need it to be live. Just seeing it’s last location would be nice 

however I tried and it doesn’t work. I’m using this 

type: map
entities:
  - entity: sensor.my_car_all_info


I assume I some how have to tell it what attribute to use for the geolocation?

**Comment by msp1974** [comment]
You need to use the device tracker entity as this is already designed to do what you want.

**Comment by BNWEIN** [comment]
Excellent!  Thanks! clearly i was being an idiot.
