### ISSUE TITLE
all_info and info stopped working 2022.3.8 to 2022.4.0

### ISSUE THREAD

**Issue by ingrove** [msp1974/homeassistant-jlrincontrol#71]
After upgrading to Home Assistant 2022.4.0 the all_info and info has stopped reporting values.  The all_info  indicates the time the last update was received and the info reports my license plate only.  I rolled back to 2022.3.8 and all values are reported.  Please let me know if there is any other information need or if I can help to debug in any way.

**Comment by msp1974** [comment]
There is currently a v2.2.1beta pre release which you will need to install to fix this. You will need to enable beta versions for the integration in HACs.  This should become a full release in a few days.

**Comment by ingrove** [comment]
Thank you.  Works as before, looking forward to the official release.

**Comment by msp1974** [comment]
Great.  Should be able to release in next few days.
