### ISSUE TITLE
Left and Right door/window swap ?

### ISSUE THREAD

**Issue by enredador** [msp1974/homeassistant-jlrincontrol#73]
Hello. Thanks for all this work! It is fantastic to integrate my new car into home assistant.

I am starting to work with it. First, I am trying to define template binary sensors for the position and status of individual doors and windows. I am surprised that the front doors (left and right) are swapped for LockStatus and Position (opening the left door is reflected in the right door attribute, and reverse).

For windows, the same -or worse-, since left and right windows are swapped for front and rear windows.

Has anybody the same issue? Browsing the code, I cannot see anything that could explain this behavior. It is may be  an issue of jlrpy or even the InControl cloud?

Thanks in advance.

**Comment by msp1974** [comment]
This must be either your car or InControl cloud as jlrpy just passes the json data as is to this integration.  It is possible to just rename them but agree its a bit rubbish.

**Comment by enredador** [comment]
Thanks. I suspect that too. I agree that in this case no changes should be made to jlrpy or the integration. I just wanted to confirm where the issue is caused. It would be nice to know if it works the same for other users.

**Comment by msp1974** [comment]
Closing this issue.
