### ISSUE TITLE
Not visible on home app on ios and precondition

### ISSUE THREAD

**Issue by allanjeevan** [msp1974/homeassistant-jlrincontrol#76]
I cant seem to add it on home app and also i cant get the service for pre conditioning the car i have a range rover velar gasoline.

**Comment by msp1974** [comment]
You'll have to give me a bit more information as to what you mean by cant seem to add it and cant get the service etc.

What are you trying to add and do you get an error?
What happens when you call the service. Again, any error?

**Comment by allanjeevan** [comment]
I cant precondition the car and i dont see the option to do. I meant i tried to add the the jlr plugin to home app on ios(homekit) but it didn't work.

**Comment by msp1974** [comment]
Sorry, I don't have much time these days and no longer have a JLR car to properly help you.  Maybe try posting on the forum and see if the users can help you.

https://community.home-assistant.io/t/jaguar-landrover-incontrol-integration/194586
