### ISSUE TITLE
Pressure and Distance converter

### ISSUE THREAD

**Issue by Oc3anAri3s** [msp1974/homeassistant-jlrincontrol#78]
Hello,

Since upgrading to HA 2022.10 I am receiving the follow warning message in the log. Does anyone know how to correct this issue? Thank you.

- Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom integration author for jlrincontrol using this method at custom_components/jlrincontrol/__init__.py, line 313: device_registry = await hass.helpers.device_registry.async_get_registry()
- Detected integration that uses pressure utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2022.4, it should be updated to use unit_conversion.PressureConverter instead. Please report issue to the custom integration author for jlrincontrol using this method at custom_components/jlrincontrol/sensor.py, line 211: pressure.convert(
- Detected integration that uses distance utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2022.4, it should be updated to use unit_conversion.DistanceConverter instead. Please report issue to the custom integration author for jlrincontrol using this method at custom_components/jlrincontrol/sensor.py, line 342: distance.convert(

**Comment by msp1974** [comment]
v2.2.2 just released with these issues fixed.  Thanks
