### ISSUE TITLE
Use device tracker to trigger automation when arriving home

### ISSUE THREAD

**Issue by ismarslomic** [msp1974/homeassistant-jlrincontrol#82]
I would like to use the device tracker of my I-Pace to trigger an automation when the car enters the Home zone. However, the location is not updated while driving so the setup doesn't work currently. Would I be able to get latest location by forcing an update with use of service `update_health_status`? Or is it impossible to retrieve the location while engine is in use?

**Comment by msp1974** [comment]
No afaik the car will not send its location whilst driving.  You can post on the hass forum page for the integration to see if anyone knows a solution or whether your specific car can be made to do so.  As i no longer have a JLR, cannot help.
