### ISSUE TITLE
Services gone

### ISSUE THREAD

**Issue by mariwing** [msp1974/homeassistant-jlrincontrol#83]
Hi,

I am running version 2022.11.5 of Home Assistant and the latest release of this component (installed via HACS).

In the last days I found that all the jlrincontrol services are gone! They give an error in my automations and script and they are not available in the developer tools.

Anyone have any idea of why this has happened? I have of course restarted but nothing changed.

**Comment by ismarslomic** [comment]
Im running latest HA and jlrincontrol and dont have this issue! Maybe you should reload the integration in the Integrations page?

**Comment by mariwing** [comment]
Thank you for your reply, that actually seemed to have fixed it!
