### ISSUE TITLE
Sensors for preconditioning status and remaining time

### ISSUE THREAD

**Issue by MrSoluz** [msp1974/homeassistant-jlrincontrol#86]
Hi,
I would like to see status if preconditioning it running or not. I have a script today with Domoticz, but I like to use HA instead. I reading EV_PRECONDITIONING_MODE form vehicleStatus. There is also EV_PRECONDITION_REMAINING_RUNTIME_MINUTES that can be useful.
That should be great to have 😃

**Comment by ismarslomic** [comment]
You already have this data available as _attributes_ of the `sensor.my_car_all_info` entity. You can easily create template sensors from the sensor attributes, see example [here](https://github.com/msp1974/homeassistant-jlrincontrol/blob/master/Recipes.md#create-your-own-template-sensor-from-the-all-info-sensor-attributes)

Here are example on the attributes that you might be interested in, copy paste this in the Developer Tools > Template to see the values.
```
{{ state_attr('sensor.my_car_all_info', 'ev status').evPreconditionOperatingStatus }}
{{ state_attr("sensor.my_car_all_info", 'ev status').evPreconditionPrioritySetting }}
{{ state_attr("sensor.my_car_all_info", 'ev status').evPreconditionRemainingRuntimeMinutes }}
{{ state_attr("sensor.my_car_all_info", 'ev status').evPreconditioningMode }}
```

**Comment by ismarslomic** [comment]
I actually missed this data my self, so I got inspired from your question and added two template sensors that show the precondition status and remaining time. Sharing the code for more inspiration! 😉 

```yaml
template:
  - sensor:
      - unique_id: my_car_precondition_remaining_runtime_minutes
        device_class: duration
        unit_of_measurement: min
        attributes:
          friendly_name: "Precondition Remaining Runtime Minutes"
        # we need to handle that remaining runtime minutes is not reset if precondition is manually switched off
        state: >-
          {% set evStatus = state_attr('sensor.my_car_all_info', 'ev status') %}

          {% if is_state('binary_sensor.template_my_car_precondition_operating_status', 'on') and evStatus != None and evStatus != 'unknown' %}
            {{ evStatus.evPreconditionRemainingRuntimeMinutes | int }}
          {% else %}
            0
          {% endif %}
  - binary_sensor:
      - unique_id: my_car_precondition_operating_status
        device_class: running
        attributes:
          friendly_name: "Precondition Operating Status"
        state: >-
          {% set evStatus = state_attr('sensor.my_car_all_info', 'ev status') %}

          {% if evStatus == None or evStatus == 'unknown' %}
            off
          {% elif evStatus.evPreconditionOperatingStatus == 'OFF' %}
            off
          {% else %}
            on
          {% endif %}
        icon: >-
          {% set evStatus = state_attr('sensor.my_car_all_info', 'ev status') %}

          {% if evStatus == None or evStatus == 'unknown' %}
            mdi:fan-alert
          {% elif evStatus.evPreconditionOperatingStatus == 'OFF' %}
            mdi:fan-off
          {% else %}
            mdi:fan
          {% endif %}
```

Showing the template sensors when precondition switched **off**
<img width="313" alt="image" src="https://user-images.githubusercontent.com/2174314/211314881-cf8478f6-6fa5-4cc3-867d-992e4582d62e.png">

Showing the template sensors when precondition switched **on**
<img width="309" alt="image" src="https://user-images.githubusercontent.com/2174314/211315326-8ad37523-0ebc-4711-a296-1464e9bb3903.png">

**Caveat**
- I choose to use `binary_sensor` (`on`/`off`) for precondition status, but the status actually got 3 states: 1) `PRECLIM` (on), `OFF` and `STARTUP` (starting). I did not bother to reflect all three states, but only on/off
- the remaining runtime minutes is updated according to the scan interval (default to `5 minutes`, can be changed in the integration Configuration, but not sure about the side effect of increasing this update)

**Comment by ismarslomic** [comment]
@msp1974 Im very new to the `jlrpy`, but do you think we could poll for precondition operating status and precondition remaining minutes more frequently, without updating the health status for complete vehicle? Or maybe subscribe for changes from the JLRs server? I know you have a section about the [Health Status Update](https://github.com/msp1974/homeassistant-jlrincontrol#health-status-update) in README, but wanted to get your input as well.

**Comment by MrSoluz** [comment]
Hi,

In the script I have been using the last three years I have used get_status every minute.
This scripted checked my Domoticz if the precondition should be on or off. I then checked EV_PRECONDITIONING_MODE if it was INACTIVE or IMMEDIATE.

But now I try to do everything I have in Domoticz in HA instread.
It is very nice in the summer to have the car at cooled all the time when we are at the beach 😊

**Comment by msp1974** [comment]
@ismarslomic - the main issue is how frequently the car updates to the JLR servers.  The jlrpy only reads from the servers.  Therefore in order to get more frequent updates of actual vehicle status you will need to force the car to update with the Health Status Update.  I am not sure if JLR will block this due to data use on their in car sim.

**Comment by MrSoluz** [comment]
I have not had any problem. But I have an extra data-SIM.
But if you like to have charging speed you need to do a full refresh.

**Comment by ismarslomic** [comment]
Alright! I think we can close this issue, as your initial question has been answered, @MrSoluz. I will however include the template sensors I shared in this issue to the recipes so other users can easily find it later on.
