### ISSUE TITLE
My i-Pace Range shows the Fuel level (which is always 0 in an EV ;-)

### ISSUE THREAD

**Issue by ganzewin** [msp1974/homeassistant-jlrincontrol#9]
![2020-04-16 20_34_28-HS12 - Home Assistant](https://user-images.githubusercontent.com/46644323/79493680-1eab2f00-8022-11ea-8bb4-095d4cc4466b.png)

**Comment by msp1974** [comment]
Yep, haven't got around to dealing with EVs yet. Happy to work on this when i have done some of the services. Are you up for assisting with some of the testing?

**Comment by ganzewin** [comment]
Ofcourse. Happy to help! Just let me know

**Comment by msp1974** [comment]
I have now had a stab at handling EVs in the latest v0.3alpha version if you would give it a try.  As my XF does not show many of the EV attributes, I have looked at [https://github.com/ardevd/jlrpy/issues/60](url) for the work that stefferber has been doing, so these may need some work when we have real data to see what is being show etc.

**Comment by ganzewin** [comment]
Hello msp1974, yes indeed the Fuel Type is now detected as electric and the "Battery Level" shows the 93% which is great! The Range is still on 0km which should be 328 km in my example.  

Keep up the good work!
![2020-04-17 17_19_53-CUSTOM - Home Assistant](https://user-images.githubusercontent.com/46644323/79585401-085bac80-80d0-11ea-9a1d-1dbb7efae5e4.png)

**Comment by msp1974** [comment]
Sorry very hard to test without one.  There was a typo in the attribute to get the range.  Do you want to update from master again and see if it works.  There is also now a new sensor which will by My i-Pace EV Battery which would be great if you can look at and share the screen shot like above.

**Comment by ganzewin** [comment]
![2020-04-17 17_46_20-CUSTOM - Home Assistant](https://user-images.githubusercontent.com/46644323/79587829-61790f80-80d3-11ea-9c36-f3dd3203d013.png)


Yes. Showing the range now (although in Miles instead of KM).

BTW. Cant find the My i-Pace EV Battery??
![2020-04-17 17_48_52-CUSTOM - Home Assistant](https://user-images.githubusercontent.com/46644323/79588092-b9b01180-80d3-11ea-9e20-c6e53fcbe8f2.png)

**Comment by msp1974** [comment]
Hmmm.. think we need to debug this.  I have added an update to master branch to allow better debugging of the data attributes and statuses for a vehicle.  Can you update.  Also, then add the following entry to your config.yaml under the jlrincontrol section.

`debug_data: true`

Then turn on debugging for this component. Do you know how to turn on debug logs for this component?  If not, add this to your configuration.yaml file

![image](https://user-images.githubusercontent.com/11211952/79596363-5ecce900-80d8-11ea-93f0-43b2c508dd5f.png)

If you then restart HA and go into Developer Tools - Logs - load the full HA log and post a copy here.

You may want to remove your reg for security before doing so. Alternatively, you can email it to me - my email is in the manifest file.

**Comment by ganzewin** [comment]
Sorry but debugging mode doesn't seem to work;

- I added the logger settings in configuration.yaml

- I installed the latest master branch

And i receive the following error;
![2020-04-17 23_25_27-Developer Tools - Home Assistant](https://user-images.githubusercontent.com/46644323/79615558-65bd2100-8103-11ea-93e3-4f31d030e9bc.png)

**Comment by ganzewin** [comment]
![2020-04-17 23_36_40-HS12 - Home Assistant](https://user-images.githubusercontent.com/46644323/79616181-b2552c00-8104-11ea-8915-64bd73627e3a.png)

Bytheway.. .In the automatic Lovelace UI i found this tab "My i-Pace EV Battery" but not in my own custom UI. So it is working...

**Comment by msp1974** [comment]
Can you double check you are running the latest version. I have double checked the code and it is definitely working.  If you look at the init.py file on this repo around line 60 you will see the config options. Can you check that matches the init.py file you are running.

**Comment by ganzewin** [comment]
I checked everything again and it is working as expected. Attached you will find the logfiles. 

If you need me to do some testing please let me know!!


[20200418 HASS JLR LOGFILE.txt](https://github.com/msp1974/homeassistant-jlrincontrol/files/4496829/20200418.HASS.JLR.LOGFILE.txt)

**Comment by msp1974** [comment]
I have done some work in the dev branch that i would appreciate if you could do some testing. See comments on issue #13 thx

**Comment by msp1974** [comment]
@ganzewin do you have any feedback on the EV sensors/services etc.  Is there anything else we need to fix or can this issue now be closed?

Thx

**Comment by ganzewin** [comment]
Sorry was not able to do testing this week but what i tested seems to work. Lets close the issues for now and i will reopen in case i find something. 

Thanks for the good work!!
