### ISSUE TITLE
Duplicate SoC Battery value as a normal sensor device

### ISSUE THREAD

**Issue by CorceiroPT** [msp1974/homeassistant-jlrincontrol#90]
I have an I-Pace and had successfully integrated the JLR InControl on a HA Core that I also have connected to my Fibaro ZWave controller. The QuickApp that I have on Fibaro controller can't get battery information and because of that I have all other information on Fibaro controller (like range, for instance) but not the State of Charge (% of the battery).

Is it possible to duplicate the battery entity with the same properties (normal sensor entity) as the "Range" one or like the "last trip" one, being only a number?

That way I could already pass it to other devices.

**Comment by ismarslomic** [comment]
I'm not completely sure what you wish to achieve. The JLR InControl integration already provides an battery sensor out of box. Could you elaborate what exactly is the issue using it, and what you mean with "normal sensor device"? I guess you are running the latest version of this integration (`v2.2.3`)?

Jinja template for reading state of the battery sensor included:
```
{{ (states('sensor.my_car_battery') )}}
```
Outputs: 100

If you really need to create an new battery sensor, you can create an sensor yourself in HA from the attributes in the `all_info` sensor by using HA [Template integration](https://www.home-assistant.io/integrations/template/) and [Templating](https://www.home-assistant.io/docs/configuration/templating/) syntax.  See also [JLR InControl Recipes](https://github.com/msp1974/homeassistant-jlrincontrol/blob/master/Recipes.md) with some examples of custom sensors.

Jinja example template:
```
{{ state_attr('sensor.my_car_all_info', 'ev status').evStateOfCharge | int  }}
``` 
Outputs: 100

**Comment by CorceiroPT** [comment]
First of all, thank you very much for your reply.

I'm just learning and exploring this home automation world. I have a controlar (Fibaro Home Center 3) where I use a third-party app that get the devices from Home Assistant (by websocket protocol) and show them on Fibaro Home Center. Is that App I have access to all of the information I can get in Home Assistant (JLR Integration) except for the battery sensor.
I was trying to understand why is that and I read on this third-party app the following:

Supported domains : {"cover","light","switch","sensor","binary_sensor","device_tracker","person"}
Excluded entity id: {"linkquality","update_state","action","click","battery","voltage","voltage","voltage","motion_sensitivity","update_available","occupancy_timeout","pressure"}

As I see "battery" on the excluded "entity id" i think that may be the issue so I was asking if there is some way to duplicate (or change) the battery sensor so that it could be uploaded by this third-party app, like the "range" is, for instance.

I already tried some assistant from the author of the other app, but didn't have an answer for now.

I know that it's not your fault and that your JLR Integration on Home Assistant is great! Thank you very much for it! The work around may be simple, but I'm only starting this and things as simples as the code you share with template examples are a lot of trouble to me (yet). I'm still learning, by myself, and reading a lot to understand where to write it or where to use it...

I have created an "auxiliary" entity on HA and some scenes to keep that entity updated with the same information as the battery JLR Incontrol sensor, but it seems that this third-party app also don't get the auxiliary entity to Fibaro Home Center...

I really don't know if there is a workaround to my issue... maybe there is, but it need to be on the thrid-party side... but I can't get any reply from there...

Any thought that can help me?

How can I change the "entity id" from the battery sensor so that it shows "sensor" instead of "battery"? I think this maybe the issue...

**Comment by ismarslomic** [comment]
If Fibaro Home Center has filtering logic to exclude entities having `battery` as part of the entity ID, then you could just rename the JLR battery sensor and remove the `battery` from the ID. 

In HA, go to **Setting** > **Entities** and search for your JLR battery sensor. Click on the entity in the list and click the **Settings** icon in the top right corner. Edit the `Entity ID` field.

**Comment by CorceiroPT** [comment]
Thank you very much @ismarslomic. Didn't know that it was so easy to change the Entity ID... I thought I needed to do it on the yaml code... That was why I was asking for help.

Already try it, but at first it didn't work. Will try to restart the systems to check if I can make it work...

Thank you very much!

**Comment by ismarslomic** [comment]
Glad to help! Closing this issue for now.
