### ISSUE TITLE
How to call the "set_max_charge_level" or "set_one_off_max_charge_level" service?

### ISSUE THREAD

**Issue by CorceiroPT** [msp1974/homeassistant-jlrincontrol#91]
I can't find any documentation on how to call or configure the services "set_max_charge_level" or "set_one_off_max_charge_level".

Does anyone with na I-Pace already tried and been successful with those services? Doesn't it need any argument to establish the max percentage stage to charge for? If so, where can we put that argument/variable?

**Comment by ismarslomic** [comment]
You can find the schema for all services in the [services.yaml](https://github.com/msp1974/homeassistant-jlrincontrol/blob/e16d944b56bf5e8b82c474780a0b808f5a82ca1d/custom_components/jlrincontrol/services.yaml). Same schema is available for each service in HA.

I have not tried this service, so Im afraid I can't help you further.

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/2174314/234871266-d101704c-0162-4710-97e0-93af773f1998.png">

**Comment by CorceiroPT** [comment]
I'm learning so much with your help! Thank you very much! I really appreciate it!
I didn't know that way of calling a service on HA.
Can you help me with another thing? How can I see what's going on on the HA when I call the service? Some kind of console Debug or something like that (to check if the services really runs).
I would like to know that to test this service.
I have the HA Core Installed on a Synology NAS. I have SSH terminal access to it, but has I has mention, I'm a newbie and don't quite know what to do (I'm only very good to follow instructions and learn from it...).
Is there a simply way to get access to a console or something like that to check the call service output?

**Comment by ismarslomic** [comment]
Glad to be of help, but HA support issues should be addressed outside of this repository.

To give you a head start please take a look at [HA Help page](https://www.home-assistant.io/help/) and the [Service Calls docs](https://www.home-assistant.io/docs/scripts/service-calls/).
