### ISSUE TITLE
How to install JLR InControl with HACS?

### ISSUE THREAD

**Issue by Powerdata44** [msp1974/homeassistant-jlrincontrol#93]
Hello all,

I am fairly new to these Github and ongoing learning with Home Assistant.. I would like to get HA link to my Land Rover... can whoever kindly guide me installing/add-on process to my HA (steps by steps)  I had seen some of you create wicked layout in Lovelace Card (want to learn on that)
Can anyone help? I would more than happy to contributions.
My email address are Powerdata44@hotmail.com if anyone can help.

Many thanks

**Comment by ismarslomic** [comment]
@Powerdata44 I assume that you would like get help installing the "JLR Home Assistant Integration" (this repo) and connecting it to your Land Rover vehicle, when you say "HA link to my Land Rover"?

The steps to achieve this is already documented in the [README.md](https://github.com/msp1974/homeassistant-jlrincontrol/blob/master/README.md), please take at chapter [Installation](https://github.com/msp1974/homeassistant-jlrincontrol#installation) and then chapter [Configuration](https://github.com/msp1974/homeassistant-jlrincontrol#configuration).

If you already got [HACS](https://hacs.xyz) (Home Assistant Community Store), you can also install it there.

**Comment by Powerdata44** [comment]
thanks for getting back to me ismarslomic :-)

I got HACS already in Home Assistant - How do I install JLR Home Assistant Integration in my Home Assistant?.....

I managed all smart devices that Home Assistant found throught my network here.... with these Github add to mine as bit rushy and ongoing learning.

**Comment by ismarslomic** [comment]
You can find it in HACS > Integrations and search for "Jaguar Landrover InControl".

**Comment by Powerdata44** [comment]
Great I found it and installed Integrations of JLR - brilliant so next steps now?  something do with configuration.yaml right?
 i got Studio Code Server installed already..

**Comment by Powerdata44** [comment]
Anyone help please?

**Comment by Powerdata44** [comment]
where shall I put my email / Password / Pins in ?

**Comment by msp1974** [comment]
Go into setting, devices and services, add integration.  Search for JLR incontrol in the list and follow the setup wizard.  If it is not in the list do a browser shift F5 refresh to reload the cache.

**Comment by Powerdata44** [comment]
Many thanks to msp1974 :-)  found it and got it on my Home Assistant Desk now...  

I saw one with photo of the car lovelace - how do i do that? and also possiable to add some info like car mileage and EcoBlu level?   how to do that?

**Comment by Powerdata44** [comment]
anyone help with Lovelace ?

**Comment by ismarslomic** [comment]
This is already documented in this repository, please take a look at the [Recipes](https://github.com/msp1974/homeassistant-jlrincontrol/blob/master/Recipes.md). 

If you are new Home Assistant user, I would recommend official documentation on [Dashboards](https://www.home-assistant.io/dashboards/) and the [Home Assistant Forum](https://community.home-assistant.io)

**Comment by Powerdata44** [comment]
Thanks ismarslomic for that -

Anyone,

can I have copy any of your designed Lovelace of JLR Card with picture of car and all keys so i can see how to put in stript code... i am trying to understand these code work. Please?

I thought it brilliant to have these system that collection information of evrything i got here. :-)
