### ISSUE TITLE
Start/Stop Charge Control is missing...

### ISSUE THREAD

**Issue by tomw1964** [msp1974/homeassistant-jlrincontrol#96]
I have a RRS P510e.  The addon is connecting and is correctly pulling data. However it doesn't seem to support a start/stop charge control. Needless to say this would be very useful since it could be integrated to the Octopus plug to only charge the car at the cheapest periods. Any clues as to where I might look to find the issue?

**Comment by dblanc42** [comment]
I too have a RRS (P400e) and you can add start and stop charging, but requires a bit of work.
I did this a few months ago, but honestly cannot recall how. I need to check this when home and get some info put here.
Regarding octopus, you should already have some degree of integration with them for THEM to trigger the charge on the cheapest tariff (if on Octopus Intelligent)
If you cannot get to have the jlrinctrol start/stop charging working, you could look at the Octopus integration, as I believe it does have a "stop/start charging" toggle

**Comment by dblanc42** [comment]
this is what my control button looks like:
![image](https://github.com/msp1974/homeassistant-jlrincontrol/assets/126181224/8f3617d7-25dd-4108-acfd-aedf7ec58e5b)

**Comment by tomw1964** [comment]
ah - yes - I can see a whole bunch services that are not visible on the card.
This is exactly what I need. 
I charge my other EVs in two modes.  

1) If I need it fully charged for the following day then looks for the cheapest 8 half hour slots. Octopus Agile prices tend to exhibit a "saw" like effect. One half is cheap, the next not and so on. 
2) if I don't need the car for a few days just look for any cheap half hour slot below XXp.  

I can do the same for the RRS now.

![image](https://github.com/msp1974/homeassistant-jlrincontrol/assets/148999626/66ab7d43-5d04-4ec3-ae27-166685bba4aa)

**Comment by dblanc42** [comment]
glad I could help a little :)
I like the ability to unlock the car and not have to give the pin every time, plus unlock from the watch using the HA app on my android watch. 
With @msp1974 work and the Octopus Energy integration, HA has really helped get all those scenarios (as you mentioned) and many more simply added.

**Comment by ismarslomic** [comment]
Closing this question as it seems that you have found a solution on your question
