### ISSUE TITLE
Issues after updating Home Assistant Core to 2023.10.5

### ISSUE THREAD

**Issue by dblanc42** [msp1974/homeassistant-jlrincontrol#97]
@msp1974 : first of all, thank you very much of the work you have done on this integration. It works brilliantly.

I am not too technical in my understanding how the integrations work, and the dependencies on the core HA SW, but when updated the core a couple of week ago, none of the vehicle data seem to work, showing "unavailable" instead of status (unfortunately, I did not take a screenshot at the time...)
But the screen below was basically "unavailable" for the battery status, and the remote functions did not work.
![image](https://github.com/msp1974/homeassistant-jlrincontrol/assets/126181224/df5b6ba3-66b9-4269-8653-7dfefd4c9ca5)

I then reverted my HA install to the backup before the core update, and all was fine again.

Is there anything you are aware of before I try again, and then dive into why this would be the case?

**Comment by dblanc42** [comment]
Tried 2023.11.1 
That seems to have resolved the issue...

**Comment by msp1974** [comment]
Glad resolved.  Will close issue.
