### ISSUE TITLE
Charging goes into "initialising" after 2 or 3 charging sessions

### ISSUE THREAD

**Issue by tomw1964** [msp1974/homeassistant-jlrincontrol#98]
I am using Octopus Agile electricity tariff which has half hour pricing. The price tends to jump around a lot. My automation works - it starts charging for 30 mins and then stops and then repeats at the next cheap 30 mins.  After doing this a few times the car won't charge and reporting _"initialising"_. I can only fix it by starting the ignition and moving the car a few centimetres. Something must be getting confused and is reset by driving. Anyone experienced the same?

**Comment by ismarslomic** [comment]
I can't see that this is an issue with the JLR plugin, but rather an limitation in your car. My best advice would be to take into account the price variations in your HA automation, to avoid changing the charging sessions too frequently.
