### ISSUE TITLE
Turn climate on/off for Discovery Sport 2021

### ISSUE THREAD

**Issue by McFarTech** [msp1974/homeassistant-jlrincontrol#99]
Hi. 

I have a Discovery Sport 2021 and i would like to be able to turn the climate on or off from within Home Assitant. I am able to lock and unlock the doors. 

I can use the Land Rover remote to do this so the car has the abilty \ functionality. Am i missing something or something else i need to setup?

**Comment by McFarTech** [comment]
Actually i have this working now.

**Comment by ismarslomic** [comment]
Closing this issue as it seems like you have found a solution on your question
